'use strict';
/* Paquets — banque 1 : cuisine, fête, école, espace (multiplication, partage, groupement, « fois plus ») */
(() => {
  // ---------------------------------------------------------------------------
  // Tirage des nombres
  // ---------------------------------------------------------------------------
  // Un problème « groupes égaux » parle de n groupes de t objets (n × t = total).
  // Chaque modèle peut donner, par grade, la plage de n et celle de t dans `plages` :
  //   [min, max] pour une plage, parmi(…) pour une liste de valeurs ;
  //   un tableau de possibilités = l'une d'elles est choisie au hasard.
  // Grade 1 : tables 2 à 5 ; grade 2 : tables jusqu'à 9 ; grade 3 : 2 chiffres × 1 chiffre.
  const parmi = (...valeurs) => ({ valeurs });
  const tire = (x, rnd, choix) => (x.valeurs ? choix(x.valeurs) : rnd(x[0], x[1]));

  const DEFAUT = {
    1: { n: [2, 5], t: [2, 5] },
    2: { n: [2, 9], t: [2, 9] },
  };
  // Grade 3 par défaut : toujours un facteur à 1 chiffre, et le diviseur à 1 chiffre pour ÷.
  const DEFAUT3 = {
    GT: [{ n: [11, 30], t: [3, 9] }, { n: [3, 9], t: [11, 30] }],
    GP: { n: [2, 6], t: [11, 30] },   // partage entre peu de parts → une part à 2 chiffres
    GG: { n: [11, 30], t: [2, 6] },   // petits groupes → beaucoup de groupes
    FP: [{ n: [2, 5], t: [11, 30] }, { n: [2, 5], t: [4, 9] }],
  };

  // Fabrique la fonction nombres() d'un modèle multiplicatif à partir de ses plages.
  function groupes(structure, plages) {
    return (niv, rnd, choix) => {
      let p = plages[niv] || (niv >= 3 ? DEFAUT3[structure] : DEFAUT[niv]);
      if (Array.isArray(p)) p = choix(p);
      const n = tire(p.n, rnd, choix), t = tire(p.t, rnd, choix);
      if (structure === 'GT') return { a: n, b: t };       // a groupes de b → total
      if (structure === 'GP') return { a: n * t, b: n };   // total partagé en b parts → une part
      if (structure === 'GG') return { a: n * t, b: t };   // total rangé par b → nombre de groupes
      return { a: t, b: n };                               // FP : a, puis « b fois plus »
    };
  }

  // ---------------------------------------------------------------------------
  // Modèles
  // ---------------------------------------------------------------------------
  const modeles = [
    // ===== GT : a groupes de b → combien en tout ? =====
    { id: 'paquets-1-001', structure: 'GT', themes: ['cuisine'],
      plages: { 1: { n: [2, 5], t: parmi(4, 6) }, 2: { n: [3, 9], t: parmi(4, 6) }, 3: { n: [11, 30], t: parmi(4, 6) } },
      texte: A => ({
        phrases: [`${A.n} aide le cuisinier de la cantine.`, `${A.Il} sort {a|boîtes} d'œufs du frigo.`, `Chaque boîte contient {b|œufs}.`],
        question: `Combien d'œufs ${A.n} a-t-${A.il} sortis du frigo ?`,
        labels: { total: 'tous les œufs', nb: 'boîtes', taille: 'œufs par boîte' },
        juste: `${A.n} a sorti {r} œufs du frigo.`,
        fausses: [`${A.n} a sorti {r} boîtes d'œufs.`, `Chaque boîte contient {r} œufs.`],
      }) },
    { id: 'paquets-1-002', structure: 'GT', themes: ['cuisine'],
      plages: { 1: { n: [2, 4], t: [4, 8] }, 2: { n: [2, 6], t: [5, 9] }, 3: { n: [2, 6], t: [12, 24] } },
      texte: () => ({
        phrases: [`Le boulanger pose {b|croissants} sur chaque plaque.`, `Il met {a|plaques} dans le four.`],
        question: `Combien de croissants le boulanger fait-il cuire ?`,
        labels: { total: 'tous les croissants', nb: 'plaques', taille: 'croissants par plaque' },
        juste: `Le boulanger fait cuire {r} croissants.`,
        fausses: [`Le boulanger met {r} plaques dans le four.`, `Il y a {r} croissants sur chaque plaque.`],
      }) },
    { id: 'paquets-1-003', structure: 'GT', themes: ['cuisine', 'fete'],
      plages: { 1: { n: [2, 5], t: parmi(4, 6) }, 2: { n: [3, 9], t: parmi(4, 6, 8) }, 3: { n: [11, 25], t: parmi(4, 6, 8) } },
      texte: A => ({
        phrases: [`Pour la fête de l'école, ${A.n} prépare {a|pizzas}.`, `${A.Il} coupe chaque pizza en {b|parts}.`],
        question: `Combien de parts de pizza ${A.n} obtient-${A.il} ?`,
        labels: { total: 'toutes les parts', nb: 'pizzas', taille: 'parts par pizza' },
        juste: `${A.n} obtient {r} parts de pizza.`,
        fausses: [`${A.n} prépare {r} pizzas.`, `Chaque pizza est coupée en {r} parts.`],
      }) },
    { id: 'paquets-1-004', structure: 'GT', themes: ['cuisine', 'fete'],
      plages: { 3: { n: [11, 30], t: [3, 8] } },
      texte: A => ({
        phrases: [`${A.n} prépare des sachets de biscuits pour la kermesse.`, `${A.Il} remplit {a|sachets}.`, `Dans chaque sachet, ${A.n} met {b|biscuits}.`],
        question: `Combien de biscuits ${A.n} utilise-t-${A.il} ?`,
        labels: { total: 'tous les biscuits', nb: 'sachets', taille: 'biscuits par sachet' },
        juste: `${A.n} utilise {r} biscuits.`,
        fausses: [`${A.n} remplit {r} sachets.`, `${A.n} met {r} biscuits dans chaque sachet.`],
      }) },
    { id: 'paquets-1-005', structure: 'GT', themes: ['cuisine'], niveaux: [1, 2],
      plages: { 1: { n: [2, 3], t: [4, 8] }, 2: { n: [2, 4], t: [6, 9] } },
      texte: A => ({
        phrases: [`Au marché, ${A.n} achète {a|filets} d'oranges.`, `Dans chaque filet, il y a {b|oranges}.`],
        question: `Combien d'oranges ${A.n} rapporte-t-${A.il} à la maison ?`,
        labels: { total: 'toutes les oranges', nb: 'filets', taille: 'oranges par filet' },
        juste: `${A.n} rapporte {r} oranges à la maison.`,
        fausses: [`${A.n} achète {r} filets d'oranges.`, `Il y a {r} oranges dans chaque filet.`],
      }) },
    { id: 'paquets-1-006', structure: 'GT', themes: ['cuisine'], niveaux: [1, 2],
      texte: A => ({
        phrases: [`Pour le goûter, ${A.n} pose {a|assiettes} sur la table.`, `Sur chaque assiette, ${A.il} met {b|fraises}.`],
        question: `Combien de fraises ${A.n} utilise-t-${A.il} en tout ?`,
        labels: { total: 'toutes les fraises', nb: 'assiettes', taille: 'fraises par assiette' },
        juste: `${A.n} utilise {r} fraises en tout.`,
        fausses: [`${A.n} pose {r} assiettes sur la table.`, `Il y a {r} fraises sur chaque assiette.`],
      }) },
    { id: 'paquets-1-007', structure: 'GT', themes: ['cuisine', 'fete'],
      plages: { 1: { n: [2, 5], t: [2, 4] }, 2: { n: [3, 9], t: [2, 5] }, 3: { n: [11, 20], t: [3, 5] } },
      texte: A => ({
        phrases: [`Pour faire un gâteau, il faut {b|œufs}.`, `${A.n} veut faire {a|gâteaux} pour la fête du quartier.`],
        question: `Combien d'œufs faut-il à ${A.n} ?`,
        labels: { total: 'tous les œufs', nb: 'gâteaux', taille: 'œufs par gâteau' },
        juste: `Il faut {r} œufs à ${A.n}.`,
        fausses: [`${A.n} veut faire {r} gâteaux.`, `Il faut {r} œufs pour un gâteau.`],
      }) },
    { id: 'paquets-1-008', structure: 'GT', themes: ['cuisine'],
      plages: { 2: { n: [2, 9], t: [3, 7] }, 3: { n: [11, 30], t: [3, 6] } },
      texte: A => ({
        phrases: [`${A.n} prépare {a|brochettes} pour le goûter.`, `Sur chaque brochette, ${A.il} enfile {b|morceaux} de fruits.`],
        question: `Combien de morceaux de fruits ${A.n} enfile-t-${A.il} en tout ?`,
        labels: { total: 'tous les morceaux', nb: 'brochettes', taille: 'morceaux par brochette' },
        juste: `${A.n} enfile {r} morceaux de fruits en tout.`,
        fausses: [`${A.n} prépare {r} brochettes.`, `Il y a {r} morceaux de fruits sur chaque brochette.`],
      }) },
    { id: 'paquets-1-009', structure: 'GT', themes: ['fete'],
      plages: { 3: { n: [11, 25], t: [3, 6] } },
      texte: A => ({
        phrases: [`Pour décorer la salle, ${A.n} accroche {a|bouquets} de ballons.`, `Chaque bouquet a {b|ballons}.`],
        question: `Combien de ballons ${A.n} accroche-t-${A.il} ?`,
        labels: { total: 'tous les ballons', nb: 'bouquets', taille: 'ballons par bouquet' },
        juste: `${A.n} accroche {r} ballons.`,
        fausses: [`${A.n} accroche {r} bouquets de ballons.`, `Chaque bouquet a {r} ballons.`],
      }) },
    { id: 'paquets-1-010', structure: 'GT', themes: ['fete'], niveaux: [1, 2],
      texte: A => ({
        phrases: [`Il y a {a|gâteaux} sur la table de la fête.`, `${A.n} plante {b|bougies} sur chaque gâteau.`],
        question: `Combien de bougies ${A.n} plante-t-${A.il} en tout ?`,
        labels: { total: 'toutes les bougies', nb: 'gâteaux', taille: 'bougies par gâteau' },
        juste: `${A.n} plante {r} bougies en tout.`,
        fausses: [`Il y a {r} gâteaux sur la table.`, `Il y a {r} bougies sur chaque gâteau.`],
      }) },
    { id: 'paquets-1-011', structure: 'GT', themes: ['fete'],
      plages: { 3: { n: [2, 6], t: [11, 30] } },
      texte: A => ({
        phrases: [`${A.n} fabrique {a|guirlandes} pour le spectacle.`, `Sur chaque guirlande, ${A.il} colle {b|étoiles} dorées.`],
        question: `Combien d'étoiles ${A.n} colle-t-${A.il} ?`,
        labels: { total: 'toutes les étoiles', nb: 'guirlandes', taille: 'étoiles par guirlande' },
        juste: `${A.n} colle {r} étoiles.`,
        fausses: [`${A.n} fabrique {r} guirlandes.`, `Il y a {r} étoiles sur chaque guirlande.`],
      }) },
    { id: 'paquets-1-012', structure: 'GT', themes: ['fete'],
      plages: { 1: { n: [3, 5], t: [2, 5] }, 2: { n: [4, 9], t: [2, 9] }, 3: { n: [11, 28], t: [3, 9] } },
      texte: () => ({
        phrases: [`À la fin de la fête, chaque invité repart avec une pochette surprise.`, `Dans chaque pochette, il y a {b|bonbons}.`, `Il y a {a|invités} à la fête.`],
        question: `Combien de bonbons faut-il pour remplir toutes les pochettes ?`,
        labels: { total: 'tous les bonbons', nb: 'invités', taille: 'bonbons par pochette' },
        juste: `Il faut {r} bonbons pour remplir toutes les pochettes.`,
        fausses: [`Il y a {r} invités à la fête.`, `Il y a {r} bonbons dans chaque pochette.`],
      }) },
    { id: 'paquets-1-013', structure: 'GT', themes: ['fete'],
      plages: { 1: { n: [2, 5], t: [3, 5] }, 2: { n: [2, 9], t: [4, 9] }, 3: [{ n: [11, 20], t: [5, 9] }, { n: [3, 9], t: [11, 20] }] },
      texte: A => ({
        phrases: [`Pour le spectacle, ${A.n} installe {a|rangées} de chaises.`, `Dans chaque rangée, il y a {b|chaises}.`],
        question: `Combien de chaises ${A.n} installe-t-${A.il} ?`,
        labels: { total: 'toutes les chaises', nb: 'rangées', taille: 'chaises par rangée' },
        juste: `${A.n} installe {r} chaises.`,
        fausses: [`${A.n} installe {r} rangées de chaises.`, `Il y a {r} chaises dans chaque rangée.`],
      }) },
    { id: 'paquets-1-014', structure: 'GT', themes: ['fete'], niveaux: [1, 2],
      plages: { 1: { n: [2, 5], t: [3, 5] }, 2: { n: [3, 9], t: [3, 7] } },
      texte: () => ({
        phrases: [`Au cirque, {a|clowns} entrent sur la piste.`, `Chaque clown jongle avec {b|balles}.`],
        question: `Combien de balles les clowns utilisent-ils en tout ?`,
        labels: { total: 'toutes les balles', nb: 'clowns', taille: 'balles par clown' },
        juste: `Les clowns utilisent {r} balles en tout.`,
        fausses: [`{r} clowns entrent sur la piste.`, `Chaque clown jongle avec {r} balles.`],
      }) },
    { id: 'paquets-1-015', structure: 'GT', themes: ['fete', 'cuisine'],
      plages: { 1: { n: [2, 5], t: parmi(2, 3) }, 2: { n: [4, 9], t: parmi(2, 3) }, 3: { n: [11, 40], t: parmi(2, 3) } },
      texte: () => ({
        phrases: [`À la fête foraine, le marchand de glaces sert {a|enfants}.`, `Chaque enfant choisit {b|boules} de glace.`],
        question: `Combien de boules de glace le marchand sert-il ?`,
        labels: { total: 'toutes les boules', nb: 'enfants', taille: 'boules par enfant' },
        juste: `Le marchand sert {r} boules de glace.`,
        fausses: [`Le marchand sert {r} enfants.`, `Chaque enfant choisit {r} boules de glace.`],
      }) },
    { id: 'paquets-1-016', structure: 'GT', themes: ['espace'],
      texte: A => ({
        phrases: [`${A.n} aide Alvin à remplir la fusée.`, `${A.Il} charge {a|caisses} de croquettes.`, `Chaque caisse contient {b|sachets}.`],
        question: `Combien de sachets de croquettes ${A.n} charge-t-${A.il} ?`,
        labels: { total: 'tous les sachets', nb: 'caisses', taille: 'sachets par caisse' },
        juste: `${A.n} charge {r} sachets de croquettes.`,
        fausses: [`${A.n} charge {r} caisses.`, `Chaque caisse contient {r} sachets.`],
      }) },
    { id: 'paquets-1-017', structure: 'GT', themes: ['espace'],
      plages: { 2: { n: [2, 9], t: [3, 8] }, 3: { n: [11, 25], t: [3, 8] } },
      texte: () => ({
        phrases: [`Sur la base spatiale, il y a {a|fusées}.`, `Chaque fusée emporte {b|astronautes}.`],
        question: `Combien d'astronautes les fusées emportent-elles en tout ?`,
        labels: { total: 'tous les astronautes', nb: 'fusées', taille: 'astronautes par fusée' },
        juste: `Les fusées emportent {r} astronautes en tout.`,
        fausses: [`Il y a {r} fusées sur la base.`, `Chaque fusée emporte {r} astronautes.`],
      }) },
    { id: 'paquets-1-018', structure: 'GT', themes: ['espace', 'ecole'], niveaux: [1, 2],
      texte: A => ({
        phrases: [`${A.n} dessine {a|planètes} sur une grande feuille.`, `Autour de chaque planète, ${A.il} dessine {b|lunes}.`],
        question: `Combien de lunes ${A.n} dessine-t-${A.il} ?`,
        labels: { total: 'toutes les lunes', nb: 'planètes', taille: 'lunes par planète' },
        juste: `${A.n} dessine {r} lunes.`,
        fausses: [`${A.n} dessine {r} planètes.`, `Il y a {r} lunes autour de chaque planète.`],
      }) },
    { id: 'paquets-1-019', structure: 'GT', themes: ['espace'],
      texte: () => ({
        phrases: [`Sur la planète, {a|robots} ramassent des cristaux.`, `Chaque robot ramasse {b|cristaux}.`],
        question: `Combien de cristaux les robots ramassent-ils en tout ?`,
        labels: { total: 'tous les cristaux', nb: 'robots', taille: 'cristaux par robot' },
        juste: `Les robots ramassent {r} cristaux en tout.`,
        fausses: [`{r} robots ramassent des cristaux.`, `Chaque robot ramasse {r} cristaux.`],
      }) },
    { id: 'paquets-1-020', structure: 'GT', themes: ['espace'], niveaux: [1, 2],
      plages: { 1: { n: [2, 4], t: [2, 5] }, 2: { n: [2, 5], t: [3, 9] } },
      texte: () => ({
        phrases: [`La fusée géante a {a|étages}.`, `Chaque étage a {b|moteurs}.`],
        question: `Combien de moteurs la fusée géante a-t-elle ?`,
        labels: { total: 'tous les moteurs', nb: 'étages', taille: 'moteurs par étage' },
        juste: `La fusée géante a {r} moteurs.`,
        fausses: [`La fusée géante a {r} étages.`, `Chaque étage a {r} moteurs.`],
      }) },
    { id: 'paquets-1-021', structure: 'GT', themes: ['ecole'], niveaux: [1, 2], sansPiege: true,
      plages: { 1: { n: [3, 5], t: [2, 5] }, 2: { n: [5, 7], t: [3, 4] } },
      texte: A => ({
        phrases: [`Dans la classe ${A.de}, les élèves sont assis par tables de {b|élèves}.`, `Il y a {a|tables} dans la classe.`],
        question: `Combien d'élèves y a-t-il dans la classe ${A.de} ?`,
        labels: { total: 'tous les élèves', nb: 'tables', taille: 'élèves par table' },
        juste: `Il y a {r} élèves dans la classe ${A.de}.`,
        fausses: [`Il y a {r} tables dans la classe.`, `Il y a {r} élèves à chaque table.`],
      }) },
    { id: 'paquets-1-022', structure: 'GT', themes: ['ecole'],
      plages: { 3: { n: [3, 9], t: parmi(12, 18, 24) } },
      texte: () => ({
        phrases: [`La maîtresse achète {a|boîtes} de crayons de couleur.`, `Dans chaque boîte, il y a {b|crayons}.`],
        question: `Combien de crayons la maîtresse achète-t-elle ?`,
        labels: { total: 'tous les crayons', nb: 'boîtes', taille: 'crayons par boîte' },
        juste: `La maîtresse achète {r} crayons.`,
        fausses: [`La maîtresse achète {r} boîtes.`, `Il y a {r} crayons dans chaque boîte.`],
      }) },
    { id: 'paquets-1-023', structure: 'GT', themes: ['ecole'],
      plages: { 3: [{ n: [3, 9], t: [11, 30] }, { n: [11, 20], t: [4, 9] }] },
      texte: A => ({
        phrases: [`${A.n} lit {b|pages} de son livre chaque soir.`, `${A.Il} lit ainsi pendant {a|soirs}.`],
        question: `Combien de pages ${A.n} lit-${A.il} en tout ?`,
        labels: { total: 'toutes les pages', nb: 'soirs', taille: 'pages par soir' },
        juste: `${A.n} lit {r} pages en tout.`,
        fausses: [`${A.n} lit pendant {r} soirs.`, `${A.n} lit {r} pages chaque soir.`],
      }) },
    { id: 'paquets-1-024', structure: 'GT', themes: ['ecole'], niveaux: [1, 2],
      plages: { 1: { n: [2, 5], t: [3, 5] }, 2: { n: [3, 7], t: [3, 6] } },
      texte: () => ({
        phrases: [`Pour la course de relais, le maître forme {a|équipes}.`, `Dans chaque équipe, il y a {b|enfants}.`],
        question: `Combien d'enfants participent à la course ?`,
        labels: { total: 'tous les enfants', nb: 'équipes', taille: 'enfants par équipe' },
        juste: `{r} enfants participent à la course.`,
        fausses: [`Le maître forme {r} équipes.`, `Il y a {r} enfants dans chaque équipe.`],
      }) },
    { id: 'paquets-1-025', structure: 'GT', themes: ['ecole'],
      plages: { 3: { n: [11, 30], t: [2, 6] } },
      texte: A => ({
        phrases: [`${A.n} a un nouveau cahier de poésie.`, `${A.Il} colle {b|gommettes} sur chaque page.`, `${A.n} décore {a|pages}.`],
        question: `Combien de gommettes ${A.n} colle-t-${A.il} ?`,
        labels: { total: 'toutes les gommettes', nb: 'pages', taille: 'gommettes par page' },
        juste: `${A.n} colle {r} gommettes.`,
        fausses: [`${A.n} décore {r} pages.`, `${A.n} colle {r} gommettes sur chaque page.`],
      }) },
    { id: 'paquets-1-026', structure: 'GT', themes: ['ecole'], niveaux: [3],
      plages: { 3: { n: [2, 5], t: [30, 55] } },
      texte: () => ({
        phrases: [`Pour la sortie de fin d'année, l'école réserve {a|autocars}.`, `Chaque autocar peut transporter {b|passagers}.`],
        question: `Combien de passagers les autocars peuvent-ils transporter en tout ?`,
        labels: { total: 'tous les passagers', nb: 'autocars', taille: 'places par autocar' },
        juste: `Les autocars peuvent transporter {r} passagers en tout.`,
        fausses: [`L'école réserve {r} autocars.`, `Chaque autocar peut transporter {r} passagers.`],
      }) },
    // « partage » dans l'énoncé, mais il faut multiplier
    { id: 'paquets-1-027', structure: 'GT', themes: ['fete'], niveaux: [2, 3],
      plages: { 2: { n: [3, 9], t: [2, 6] }, 3: { n: [3, 8], t: [11, 20] } },
      texte: A => ({
        phrases: [`Pour son anniversaire, ${A.n} partage des bonbons avec ses amis.`, `${A.Il} donne {b|bonbons} à chacun de ses {a|amis}.`],
        question: `Combien de bonbons ${A.n} donne-t-${A.il} en tout ?`,
        labels: { total: 'tous les bonbons donnés', nb: 'amis', taille: 'pour un ami' },
        juste: `${A.n} donne {r} bonbons en tout.`,
        fausses: [`${A.n} a {r} amis.`, `Chaque ami reçoit {r} bonbons.`],
      }) },
    { id: 'paquets-1-028', structure: 'GT', themes: ['cuisine'],
      plages: { 1: { n: [2, 5], t: [2, 4] }, 2: { n: [3, 9], t: [2, 4] }, 3: { n: [11, 30], t: [2, 4] } },
      texte: A => ({
        phrases: [`${A.n} a préparé des crêpes pour le goûter du club.`, `Les {a|enfants} du club mangent {b|crêpes} chacun.`],
        question: `Combien de crêpes les enfants mangent-ils en tout ?`,
        labels: { total: 'toutes les crêpes', nb: 'enfants', taille: 'crêpes par enfant' },
        juste: `Les enfants mangent {r} crêpes en tout.`,
        fausses: [`Il y a {r} enfants au club.`, `Chaque enfant mange {r} crêpes.`],
      }) },
    { id: 'paquets-1-029', structure: 'GT', themes: ['espace', 'cuisine'],
      texte: () => ({
        phrases: [`Pendant son long voyage, Alvin prend {a|repas}.`, `À chaque repas, Alvin mange {b|croquettes}.`],
        question: `Combien de croquettes Alvin mange-t-il pendant le voyage ?`,
        labels: { total: 'toutes les croquettes', nb: 'repas', taille: 'croquettes par repas' },
        juste: `Alvin mange {r} croquettes pendant le voyage.`,
        fausses: [`Alvin prend {r} repas.`, `Alvin mange {r} croquettes à chaque repas.`],
      }) },
    { id: 'paquets-1-030', structure: 'GT', themes: ['ecole'],
      plages: { 1: { n: [2, 5], t: parmi(5, 10) }, 2: { n: [3, 9], t: [5, 9] }, 3: { n: [3, 9], t: [15, 40] } },
      texte: () => ({
        phrases: [`La bibliothèque de l'école a {a|étagères}.`, `Sur chaque étagère, on range {b|livres}.`],
        question: `Combien de livres peut-on ranger dans la bibliothèque ?`,
        labels: { total: 'tous les livres', nb: 'étagères', taille: 'livres par étagère' },
        juste: `On peut ranger {r} livres dans la bibliothèque.`,
        fausses: [`Il y a {r} étagères dans la bibliothèque.`, `On range {r} livres sur chaque étagère.`],
      }) },

    // ===== GP : a partagé en b parts égales → combien dans une part ? =====
    { id: 'paquets-1-031', structure: 'GP', themes: ['cuisine'],
      plages: { 3: { n: [2, 6], t: [11, 25] } },
      texte: A => ({
        phrases: [`${A.n} a {a|cerises}.`, `${A.Il} les répartit dans {b|bols}, avec le même nombre de cerises dans chaque bol.`],
        question: `Combien de cerises ${A.n} met-${A.il} dans chaque bol ?`,
        labels: { total: 'toutes les cerises', nb: 'bols', taille: 'cerises par bol' },
        juste: `${A.n} met {r} cerises dans chaque bol.`,
        fausses: [`${A.n} remplit {r} bols.`, `${A.n} a {r} cerises en tout.`],
      }) },
    { id: 'paquets-1-032', structure: 'GP', themes: ['cuisine'], niveaux: [1, 2],
      plages: { 1: { n: [2, 5], t: [2, 4] }, 2: { n: [3, 9], t: [2, 4] } },
      texte: A => ({
        phrases: [`Pour le repas, il y a {a|parts} de pizza.`, `${A.n} les partage équitablement entre {b|enfants}.`],
        question: `Combien de parts de pizza chaque enfant mange-t-il ?`,
        labels: { total: 'toutes les parts', nb: 'enfants', taille: 'parts par enfant' },
        juste: `Chaque enfant mange {r} parts de pizza.`,
        fausses: [`Il y a {r} enfants à table.`, `Il y a {r} parts de pizza en tout.`],
      }) },
    { id: 'paquets-1-033', structure: 'GP', themes: ['cuisine'],
      plages: { 1: { n: [2, 4], t: [2, 5] }, 2: { n: [2, 6], t: [3, 9] }, 3: { n: [2, 5], t: [11, 20] } },
      texte: () => ({
        phrases: [`Le cuisinier prépare {a|litres} de soupe.`, `Il verse la même quantité dans {b|marmites}.`],
        question: `Combien de litres de soupe y a-t-il dans chaque marmite ?`,
        labels: { total: 'toute la soupe', nb: 'marmites', taille: 'litres par marmite' },
        juste: `Il y a {r} litres de soupe dans chaque marmite.`,
        fausses: [`Le cuisinier remplit {r} marmites.`, `Le cuisinier prépare {r} litres de soupe.`],
      }) },
    { id: 'paquets-1-034', structure: 'GP', themes: ['cuisine'], niveaux: [1, 2],
      plages: { 1: { n: [2, 4], t: [3, 5] }, 2: { n: [2, 5], t: [4, 9] } },
      texte: A => ({
        phrases: [`${A.n} a cueilli {a|pommes}.`, `${A.Il} veut faire {b|tartes} avec toutes ces pommes.`, `${A.Il} met le même nombre de pommes dans chaque tarte.`],
        question: `Combien de pommes ${A.n} met-${A.il} dans chaque tarte ?`,
        labels: { total: 'toutes les pommes', nb: 'tartes', taille: 'pommes par tarte' },
        juste: `${A.n} met {r} pommes dans chaque tarte.`,
        fausses: [`${A.n} fait {r} tartes.`, `${A.n} a cueilli {r} pommes.`],
      }) },
    { id: 'paquets-1-035', structure: 'GP', themes: ['cuisine'],
      plages: { 2: { n: [2, 9], t: [3, 9] }, 3: { n: [2, 6], t: [11, 20] } },
      texte: () => ({
        phrases: [`La boulangère a fait {a|madeleines}.`, `Elle les range dans {b|sachets}.`, `Chaque sachet contient le même nombre de madeleines.`],
        question: `Combien de madeleines y a-t-il dans chaque sachet ?`,
        labels: { total: 'toutes les madeleines', nb: 'sachets', taille: 'madeleines par sachet' },
        juste: `Il y a {r} madeleines dans chaque sachet.`,
        fausses: [`La boulangère remplit {r} sachets.`, `La boulangère a fait {r} madeleines.`],
      }) },
    { id: 'paquets-1-036', structure: 'GP', themes: ['fete'],
      plages: { 1: { n: [3, 5], t: [2, 5] }, 2: { n: [3, 9], t: [2, 9] }, 3: { n: [3, 6], t: [11, 20] } },
      texte: A => ({
        phrases: [`À la chasse au trésor, ${A.n} et ses amis trouvent {a|chocolats}.`, `Les {b|enfants} se partagent les chocolats de façon équitable.`],
        question: `Combien de chocolats chaque enfant reçoit-il ?`,
        labels: { total: 'tous les chocolats', nb: 'enfants', taille: 'pour un enfant' },
        juste: `Chaque enfant reçoit {r} chocolats.`,
        fausses: [`Il y a {r} enfants.`, `Les enfants trouvent {r} chocolats en tout.`],
      }) },
    { id: 'paquets-1-037', structure: 'GP', themes: ['fete', 'jardin'], niveaux: [1, 2],
      plages: { 2: { n: [2, 6], t: [3, 9] } },
      texte: A => ({
        phrases: [`${A.n} a {a|ballons} pour décorer le jardin.`, `${A.Il} les accroche aux {b|arbres}, autant sur chaque arbre.`],
        question: `Combien de ballons ${A.n} accroche-t-${A.il} sur chaque arbre ?`,
        labels: { total: 'tous les ballons', nb: 'arbres', taille: 'ballons par arbre' },
        juste: `${A.n} accroche {r} ballons sur chaque arbre.`,
        fausses: [`Il y a {r} arbres dans le jardin.`, `${A.n} a {r} ballons en tout.`],
      }) },
    { id: 'paquets-1-038', structure: 'GP', themes: ['fete'],
      plages: { 3: { n: [2, 6], t: [11, 25] } },
      texte: A => ({
        phrases: [`${A.n} gagne {a|autocollants} à la tombola.`, `${A.Il} les distribue tous à ses {b|cousins}, en parts égales.`],
        question: `Combien d'autocollants chaque cousin reçoit-il ?`,
        labels: { total: 'tous les autocollants', nb: 'cousins', taille: 'pour un cousin' },
        juste: `Chaque cousin reçoit {r} autocollants.`,
        fausses: [`${A.n} a {r} cousins.`, `${A.n} gagne {r} autocollants.`],
      }) },
    { id: 'paquets-1-039', structure: 'GP', themes: ['fete', 'ecole'],
      plages: { 1: { n: [2, 4], t: [3, 5] }, 2: { n: [2, 6], t: [3, 9] }, 3: { n: [3, 6], t: [11, 16] } },
      texte: () => ({
        phrases: [`À la kermesse, {a|enfants} participent au grand jeu.`, `On forme {b|équipes} avec le même nombre d'enfants.`],
        question: `Combien d'enfants y a-t-il dans chaque équipe ?`,
        labels: { total: 'tous les enfants', nb: 'équipes', taille: 'enfants par équipe' },
        juste: `Il y a {r} enfants dans chaque équipe.`,
        fausses: [`On forme {r} équipes.`, `{r} enfants participent au grand jeu.`],
      }) },
    { id: 'paquets-1-040', structure: 'GP', themes: ['fete'], niveaux: [1, 2],
      texte: () => ({
        phrases: [`Le magicien a {a|foulards}.`, `Il les cache dans {b|chapeaux}, le même nombre dans chaque chapeau.`],
        question: `Combien de foulards le magicien cache-t-il dans chaque chapeau ?`,
        labels: { total: 'tous les foulards', nb: 'chapeaux', taille: 'foulards par chapeau' },
        juste: `Le magicien cache {r} foulards dans chaque chapeau.`,
        fausses: [`Le magicien a {r} chapeaux.`, `Le magicien a {r} foulards en tout.`],
      }) },
    { id: 'paquets-1-041', structure: 'GP', themes: ['fete', 'cuisine'],
      plages: { 3: { n: [2, 5], t: [11, 20] } },
      texte: A => ({
        phrases: [`${A.n} a préparé {a|petits gâteaux}.`, `${A.Il} les pose sur {b|plateaux}, autant sur chaque plateau.`],
        question: `Combien de petits gâteaux y a-t-il sur chaque plateau ?`,
        labels: { total: 'tous les gâteaux', nb: 'plateaux', taille: 'gâteaux par plateau' },
        juste: `Il y a {r} petits gâteaux sur chaque plateau.`,
        fausses: [`${A.n} remplit {r} plateaux.`, `${A.n} a préparé {r} petits gâteaux.`],
      }) },
    { id: 'paquets-1-042', structure: 'GP', themes: ['espace'],
      plages: { 3: { n: [2, 6], t: [11, 30] } },
      texte: () => ({
        phrases: [`Alvin rapporte {a|pierres de lune} de son voyage.`, `Il les range dans {b|boîtes}, autant dans chaque boîte.`],
        question: `Combien de pierres de lune Alvin met-il dans chaque boîte ?`,
        labels: { total: 'toutes les pierres', nb: 'boîtes', taille: 'pierres par boîte' },
        juste: `Alvin met {r} pierres de lune dans chaque boîte.`,
        fausses: [`Alvin remplit {r} boîtes.`, `Alvin rapporte {r} pierres de lune.`],
      }) },
    { id: 'paquets-1-043', structure: 'GP', themes: ['espace'],
      texte: () => ({
        phrases: [`La station spatiale a {a|bidons} de carburant.`, `On les répartit équitablement entre {b|fusées}.`],
        question: `Combien de bidons chaque fusée reçoit-elle ?`,
        labels: { total: 'tous les bidons', nb: 'fusées', taille: 'bidons par fusée' },
        juste: `Chaque fusée reçoit {r} bidons.`,
        fausses: [`Il y a {r} fusées.`, `La station a {r} bidons de carburant.`],
      }) },
    { id: 'paquets-1-044', structure: 'GP', themes: ['espace', 'cuisine'],
      plages: { 2: { n: [2, 6], t: [3, 9] }, 3: { n: [3, 6], t: [11, 20] } },
      texte: () => ({
        phrases: [`Dans la station, {b|astronautes} se partagent {a|barres de céréales}.`, `Chacun reçoit le même nombre de barres.`],
        question: `Combien de barres de céréales chaque astronaute reçoit-il ?`,
        labels: { total: 'toutes les barres', nb: 'astronautes', taille: 'barres par astronaute' },
        juste: `Chaque astronaute reçoit {r} barres de céréales.`,
        fausses: [`Il y a {r} astronautes dans la station.`, `Les astronautes se partagent {r} barres de céréales.`],
      }) },
    { id: 'paquets-1-045', structure: 'GP', themes: ['espace'],
      plages: { 3: { n: [3, 9], t: [11, 40] } },
      texte: A => ({
        phrases: [`${A.n} trouve {a|cristaux} dans une grotte.`, `${A.Il} les partage équitablement entre {b|robots}.`],
        question: `Combien de cristaux chaque robot reçoit-il ?`,
        labels: { total: 'tous les cristaux', nb: 'robots', taille: 'pour un robot' },
        juste: `Chaque robot reçoit {r} cristaux.`,
        fausses: [`Il y a {r} robots.`, `${A.n} trouve {r} cristaux.`],
      }) },
    { id: 'paquets-1-046', structure: 'GP', themes: ['espace'], niveaux: [1, 2],
      plages: { 1: { n: [2, 5], t: [2, 4] }, 2: { n: [2, 5], t: [2, 6] } },
      texte: () => ({
        phrases: [`Ce matin, {a|astronautes} partent explorer la planète.`, `Ils montent dans {b|petits vaisseaux}, avec le même nombre d'astronautes dans chacun.`],
        question: `Combien d'astronautes y a-t-il dans chaque petit vaisseau ?`,
        labels: { total: 'tous les astronautes', nb: 'vaisseaux', taille: 'astronautes par vaisseau' },
        juste: `Il y a {r} astronautes dans chaque petit vaisseau.`,
        fausses: [`Les astronautes prennent {r} petits vaisseaux.`, `{r} astronautes partent explorer la planète.`],
      }) },
    { id: 'paquets-1-047', structure: 'GP', themes: ['ecole'],
      plages: { 1: { n: [2, 5], t: [3, 5] }, 2: { n: [4, 8], t: [3, 9] }, 3: { n: [4, 8], t: [11, 15] } },
      texte: () => ({
        phrases: [`La maîtresse a {a|feutres}.`, `Elle les répartit sur les {b|tables} de la classe, autant sur chaque table.`],
        question: `Combien de feutres y a-t-il sur chaque table ?`,
        labels: { total: 'tous les feutres', nb: 'tables', taille: 'feutres par table' },
        juste: `Il y a {r} feutres sur chaque table.`,
        fausses: [`Il y a {r} tables dans la classe.`, `La maîtresse a {r} feutres en tout.`],
      }) },
    { id: 'paquets-1-048', structure: 'GP', themes: ['ecole'], niveaux: [2, 3],
      plages: { 2: { n: [2, 6], t: [3, 9] }, 3: { n: [3, 8], t: [12, 28] } },
      texte: () => ({
        phrases: [`Le directeur reçoit {a|dictionnaires} pour l'école.`, `Il les partage équitablement entre {b|classes}.`],
        question: `Combien de dictionnaires chaque classe reçoit-elle ?`,
        labels: { total: 'tous les dictionnaires', nb: 'classes', taille: 'pour une classe' },
        juste: `Chaque classe reçoit {r} dictionnaires.`,
        fausses: [`L'école a {r} classes.`, `Le directeur reçoit {r} dictionnaires.`],
      }) },
    { id: 'paquets-1-049', structure: 'GP', themes: ['ecole'],
      texte: A => ({
        phrases: [`À la récréation, ${A.n} a {a|billes}.`, `${A.Il} fait {b|tas} avec le même nombre de billes.`],
        question: `Combien de billes y a-t-il dans chaque tas ?`,
        labels: { total: 'toutes les billes', nb: 'tas', taille: 'billes par tas' },
        juste: `Il y a {r} billes dans chaque tas.`,
        fausses: [`${A.n} fait {r} tas.`, `${A.n} a {r} billes en tout.`],
      }) },
    { id: 'paquets-1-050', structure: 'GP', themes: ['ecole'], niveaux: [1, 2], sansPiege: true,
      plages: { 1: { n: [2, 5], t: [3, 5] }, 2: { n: [3, 7], t: [3, 4] } },
      texte: A => ({
        phrases: [`Les {a|élèves} de la classe ${A.de} préparent un exposé.`, `Ils travaillent en {b|groupes} de même taille.`],
        question: `Combien d'élèves y a-t-il dans chaque groupe ?`,
        labels: { total: 'tous les élèves', nb: 'groupes', taille: 'élèves par groupe' },
        juste: `Il y a {r} élèves dans chaque groupe.`,
        fausses: [`Les élèves forment {r} groupes.`, `Il y a {r} élèves dans la classe.`],
      }) },
    { id: 'paquets-1-051', structure: 'GP', themes: ['ecole'], niveaux: [2, 3],
      plages: { 2: { n: [2, 5], t: [6, 9] }, 3: { n: [2, 5], t: [11, 16] } },
      texte: () => ({
        phrases: [`Pour la sortie au musée, {a|élèves} montent dans des minibus.`, `Il y a {b|minibus}, avec le même nombre d'élèves dans chacun.`],
        question: `Combien d'élèves y a-t-il dans chaque minibus ?`,
        labels: { total: 'tous les élèves', nb: 'minibus', taille: 'élèves par minibus' },
        juste: `Il y a {r} élèves dans chaque minibus.`,
        fausses: [`Il y a {r} minibus.`, `{r} élèves partent au musée.`],
      }) },
    // « fois » dans l'énoncé, mais il faut diviser
    { id: 'paquets-1-052', structure: 'GP', themes: ['cuisine'], niveaux: [2, 3],
      plages: { 2: { n: [2, 5], t: [5, 9] }, 3: { n: [2, 5], t: [12, 30] } },
      texte: () => ({
        phrases: [`Le pâtissier fait cuire {a|biscuits} en {b|fois}.`, `À chaque fois, il met le même nombre de biscuits dans le four.`],
        question: `Combien de biscuits le pâtissier met-il dans le four à chaque fois ?`,
        labels: { total: 'tous les biscuits', nb: 'fois au four', taille: 'biscuits à chaque fois' },
        juste: `Le pâtissier met {r} biscuits dans le four à chaque fois.`,
        fausses: [`Le pâtissier fait cuire {r} biscuits en tout.`, `Le pâtissier met les biscuits au four {r} fois.`],
      }) },
    // « gagnent » dans l'énoncé, mais il faut diviser
    { id: 'paquets-1-053', structure: 'GP', themes: ['fete'], niveaux: [2, 3],
      plages: { 2: { n: [3, 9], t: [2, 9] }, 3: { n: [3, 5], t: [11, 25] } },
      texte: A => ({
        phrases: [`À la kermesse, ${A.n} et ses amis gagnent {a|tickets} en tout.`, `Ils sont {b|enfants}, et chacun a gagné le même nombre de tickets.`],
        question: `Combien de tickets chaque enfant a-t-il gagnés ?`,
        labels: { total: 'tous les tickets', nb: 'enfants', taille: 'pour un enfant' },
        juste: `Chaque enfant a gagné {r} tickets.`,
        fausses: [`Il y a {r} enfants.`, `Les enfants ont gagné {r} tickets en tout.`],
      }) },
    { id: 'paquets-1-054', structure: 'GP', themes: ['espace'], niveaux: [2, 3],
      plages: { 3: { n: [2, 9], t: [11, 60] } },
      texte: () => ({
        phrases: [`Le robot explorateur parcourt {a|mètres} en {b|minutes}.`, `Chaque minute, il parcourt la même distance.`],
        question: `Combien de mètres le robot parcourt-il en une minute ?`,
        labels: { total: 'tout le trajet', nb: 'minutes', taille: 'en une minute' },
        juste: `Le robot parcourt {r} mètres en une minute.`,
        fausses: [`Le robot roule pendant {r} minutes.`, `Le robot parcourt {r} mètres en tout.`],
      }) },
    { id: 'paquets-1-055', structure: 'GP', themes: ['cuisine', 'fete'], niveaux: [1, 2],
      plages: { 2: { n: [2, 6], t: [3, 6] } },
      texte: A => ({
        phrases: [`${A.n} a une boîte de {a|chocolats}.`, `${A.Il} les offre tous à ses {b|voisins}, et chacun reçoit le même nombre de chocolats.`],
        question: `Combien de chocolats chaque voisin reçoit-il ?`,
        labels: { total: 'tous les chocolats', nb: 'voisins', taille: 'pour un voisin' },
        juste: `Chaque voisin reçoit {r} chocolats.`,
        fausses: [`${A.n} a {r} voisins.`, `La boîte contient {r} chocolats.`],
      }) },
    { id: 'paquets-1-056', structure: 'GP', themes: ['ecole'], niveaux: [1, 2],
      plages: { 1: { n: [2, 3], t: [4, 8] }, 2: { n: [2, 4], t: [5, 9] } },
      texte: () => ({
        phrases: [`Pour la photo de classe, {a|élèves} se placent sur {b|rangées}.`, `Il y a le même nombre d'élèves sur chaque rangée.`],
        question: `Combien d'élèves y a-t-il sur chaque rangée ?`,
        labels: { total: 'tous les élèves', nb: 'rangées', taille: 'élèves par rangée' },
        juste: `Il y a {r} élèves sur chaque rangée.`,
        fausses: [`Il y a {r} rangées.`, `{r} élèves sont sur la photo.`],
      }) },

    // ===== GG : a rangés par b → combien de groupes ? =====
    { id: 'paquets-1-057', structure: 'GG', themes: ['cuisine'],
      plages: { 2: { n: [2, 9], t: parmi(4, 6) }, 3: { n: [11, 25], t: parmi(4, 6) } },
      texte: A => ({
        phrases: [`${A.n} ramasse {a|œufs} à la ferme.`, `${A.Il} les range dans des boîtes de {b|œufs}.`],
        question: `Combien de boîtes ${A.n} remplit-${A.il} ?`,
        labels: { total: 'tous les œufs', nb: 'boîtes', taille: 'œufs par boîte' },
        juste: `${A.n} remplit {r} boîtes.`,
        fausses: [`${A.n} ramasse {r} œufs.`, `Il y a {r} œufs dans chaque boîte.`],
      }) },
    // « chaque » dans l'énoncé, mais on cherche le nombre de groupes
    { id: 'paquets-1-058', structure: 'GG', themes: ['cuisine', 'fete'],
      plages: { 2: { n: [2, 9], t: [2, 4] }, 3: { n: [11, 25], t: [2, 4] } },
      texte: A => ({
        phrases: [`${A.n} a préparé {a|crêpes} pour ses invités.`, `Chaque invité mange {b|crêpes}, et il n'en reste aucune.`],
        question: `Combien d'invités y a-t-il ?`,
        labels: { total: 'toutes les crêpes', nb: 'invités', taille: 'crêpes par invité' },
        juste: `Il y a {r} invités.`,
        fausses: [`Chaque invité mange {r} crêpes.`, `${A.n} a préparé {r} crêpes.`],
      }) },
    { id: 'paquets-1-059', structure: 'GG', themes: ['cuisine'],
      plages: { 2: { n: [2, 9], t: [3, 8] }, 3: { n: [11, 30], t: [3, 8] } },
      texte: () => ({
        phrases: [`Le pâtissier a {a|framboises}.`, `Il met {b|framboises} sur chaque tartelette.`],
        question: `Combien de tartelettes le pâtissier peut-il décorer ?`,
        labels: { total: 'toutes les framboises', nb: 'tartelettes', taille: 'framboises par tartelette' },
        juste: `Le pâtissier peut décorer {r} tartelettes.`,
        fausses: [`Le pâtissier met {r} framboises sur chaque tartelette.`, `Le pâtissier a {r} framboises.`],
      }) },
    { id: 'paquets-1-060', structure: 'GG', themes: ['cuisine'],
      texte: A => ({
        phrases: [`${A.n} a fait cuire {a|biscuits}.`, `${A.Il} met {b|biscuits} dans chaque sachet.`],
        question: `Combien de sachets ${A.n} peut-${A.il} remplir ?`,
        labels: { total: 'tous les biscuits', nb: 'sachets', taille: 'biscuits par sachet' },
        juste: `${A.n} peut remplir {r} sachets.`,
        fausses: [`${A.n} met {r} biscuits dans chaque sachet.`, `${A.n} a fait cuire {r} biscuits.`],
      }) },
    { id: 'paquets-1-061', structure: 'GG', themes: ['cuisine', 'ecole'],
      plages: { 2: { n: [2, 9], t: parmi(4, 6, 8) }, 3: { n: [11, 30], t: parmi(4, 6, 8) } },
      texte: () => ({
        phrases: [`À la cantine, il y a {a|bouteilles} d'eau.`, `On les range par packs de {b|bouteilles}.`],
        question: `Combien de packs obtient-on ?`,
        labels: { total: 'toutes les bouteilles', nb: 'packs', taille: 'bouteilles par pack' },
        juste: `On obtient {r} packs.`,
        fausses: [`Il y a {r} bouteilles dans chaque pack.`, `Il y a {r} bouteilles d'eau à la cantine.`],
      }) },
    { id: 'paquets-1-062', structure: 'GG', themes: ['fete'],
      plages: { 2: { n: [2, 9], t: [4, 8] }, 3: { n: [11, 20], t: [4, 8] } },
      texte: () => ({
        phrases: [`Pour le repas de fête, il y a {a|invités}.`, `On installe des tables de {b|places}.`, `Toutes les places sont occupées.`],
        question: `Combien de tables faut-il ?`,
        labels: { total: 'tous les invités', nb: 'tables', taille: 'places par table' },
        juste: `Il faut {r} tables.`,
        fausses: [`Il y a {r} invités.`, `Chaque table a {r} places.`],
      }) },
    { id: 'paquets-1-063', structure: 'GG', themes: ['fete', 'ecole'],
      plages: { 2: { n: [2, 9], t: [3, 6] }, 3: { n: [11, 16], t: [4, 9] } },
      texte: () => ({
        phrases: [`À la fête de l'école, {a|enfants} jouent aux grands jeux.`, `La maîtresse fait des équipes de {b|enfants}.`],
        question: `Combien d'équipes la maîtresse forme-t-elle ?`,
        labels: { total: 'tous les enfants', nb: 'équipes', taille: 'enfants par équipe' },
        juste: `La maîtresse forme {r} équipes.`,
        fausses: [`Il y a {r} enfants dans chaque équipe.`, `{r} enfants jouent aux grands jeux.`],
      }) },
    { id: 'paquets-1-064', structure: 'GG', themes: ['fete'],
      plages: { 3: { n: [11, 20], t: [3, 6] } },
      texte: A => ({
        phrases: [`${A.n} a gonflé {a|ballons}.`, `${A.Il} fait des bouquets de {b|ballons}.`],
        question: `Combien de bouquets ${A.n} peut-${A.il} faire ?`,
        labels: { total: 'tous les ballons', nb: 'bouquets', taille: 'ballons par bouquet' },
        juste: `${A.n} peut faire {r} bouquets.`,
        fausses: [`Chaque bouquet a {r} ballons.`, `${A.n} a gonflé {r} ballons.`],
      }) },
    { id: 'paquets-1-065', structure: 'GG', themes: ['fete'],
      plages: { 3: { n: [11, 25], t: [3, 7] } },
      texte: () => ({
        phrases: [`Pour décorer les tables de la fête, le fleuriste a {a|roses}.`, `Il met {b|roses} dans chaque vase.`],
        question: `Combien de vases le fleuriste remplit-il ?`,
        labels: { total: 'toutes les roses', nb: 'vases', taille: 'roses par vase' },
        juste: `Le fleuriste remplit {r} vases.`,
        fausses: [`Le fleuriste met {r} roses dans chaque vase.`, `Le fleuriste a {r} roses.`],
      }) },
    { id: 'paquets-1-066', structure: 'GG', themes: ['fete'],
      plages: { 2: { n: [2, 9], t: [2, 6] }, 3: { n: [6, 12], t: [4, 9] } },
      texte: () => ({
        phrases: [`À la fête, {a|enfants} montent dans le petit train.`, `Chaque wagon a {b|places}, et tous les wagons sont pleins.`],
        question: `Combien de wagons le petit train a-t-il ?`,
        labels: { total: 'tous les enfants', nb: 'wagons', taille: 'places par wagon' },
        juste: `Le petit train a {r} wagons.`,
        fausses: [`Chaque wagon a {r} places.`, `{r} enfants montent dans le petit train.`],
      }) },
    { id: 'paquets-1-067', structure: 'GG', themes: ['espace'],
      plages: { 2: { n: [2, 9], t: [2, 8] }, 3: { n: [11, 20], t: [3, 8] } },
      texte: () => ({
        phrases: [`Sur la base, {a|astronautes} attendent pour rejoindre la station spatiale.`, `La navette emmène {b|astronautes} à chaque voyage.`],
        question: `Combien de voyages la navette doit-elle faire ?`,
        labels: { total: 'tous les astronautes', nb: 'voyages', taille: 'astronautes par voyage' },
        juste: `La navette doit faire {r} voyages.`,
        fausses: [`La navette emmène {r} astronautes à chaque voyage.`, `{r} astronautes attendent sur la base.`],
      }) },
    { id: 'paquets-1-068', structure: 'GG', themes: ['espace'],
      plages: { 3: { n: [11, 40], t: [3, 9] } },
      texte: () => ({
        phrases: [`Les robots de la mine ont trouvé {a|cristaux}.`, `Ils les rangent dans des sacs de {b|cristaux}.`],
        question: `Combien de sacs les robots remplissent-ils ?`,
        labels: { total: 'tous les cristaux', nb: 'sacs', taille: 'cristaux par sac' },
        juste: `Les robots remplissent {r} sacs.`,
        fausses: [`Les robots mettent {r} cristaux dans chaque sac.`, `Les robots ont trouvé {r} cristaux.`],
      }) },
    { id: 'paquets-1-069', structure: 'GG', themes: ['espace'],
      plages: { 2: { n: [2, 9], t: [2, 6] }, 3: { n: [11, 30], t: [2, 6] } },
      texte: () => ({
        phrases: [`Alvin a pris {a|photos} de planètes.`, `Il les colle dans son carnet de voyage, {b|photos} par page.`],
        question: `Combien de pages Alvin remplit-il ?`,
        labels: { total: 'toutes les photos', nb: 'pages', taille: 'photos par page' },
        juste: `Alvin remplit {r} pages.`,
        fausses: [`Alvin colle {r} photos par page.`, `Alvin a pris {r} photos.`],
      }) },
    { id: 'paquets-1-070', structure: 'GG', themes: ['espace'],
      plages: { 3: { n: [11, 25], t: [3, 6] } },
      texte: () => ({
        phrases: [`Le grand vaisseau a {a|sièges}.`, `Les sièges sont alignés en rangées de {b|sièges}.`],
        question: `Combien de rangées de sièges y a-t-il ?`,
        labels: { total: 'tous les sièges', nb: 'rangées', taille: 'sièges par rangée' },
        juste: `Il y a {r} rangées de sièges.`,
        fausses: [`Il y a {r} sièges dans chaque rangée.`, `Le grand vaisseau a {r} sièges.`],
      }) },
    { id: 'paquets-1-071', structure: 'GG', themes: ['espace'],
      plages: { 2: { n: [2, 9], t: [2, 4] }, 3: { n: [11, 30], t: [2, 4] } },
      texte: A => ({
        phrases: [`Sur cette planète, chaque habitant a {b|antennes}.`, `${A.n} compte {a|antennes} sur la place du village.`],
        question: `Combien d'habitants y a-t-il sur la place ?`,
        labels: { total: 'toutes les antennes', nb: 'habitants', taille: 'antennes par habitant' },
        juste: `Il y a {r} habitants sur la place.`,
        fausses: [`Chaque habitant a {r} antennes.`, `${A.n} compte {r} antennes.`],
      }) },
    { id: 'paquets-1-072', structure: 'GG', themes: ['ecole'],
      plages: { 3: { n: [11, 20], t: [4, 9] } },
      texte: () => ({
        phrases: [`La maîtresse a {a|crayons} neufs.`, `Elle les met dans des pots de {b|crayons}.`],
        question: `Combien de pots la maîtresse remplit-elle ?`,
        labels: { total: 'tous les crayons', nb: 'pots', taille: 'crayons par pot' },
        juste: `La maîtresse remplit {r} pots.`,
        fausses: [`La maîtresse met {r} crayons dans chaque pot.`, `La maîtresse a {r} crayons neufs.`],
      }) },
    { id: 'paquets-1-073', structure: 'GG', themes: ['ecole', 'sport'], niveaux: [2],
      plages: { 2: { n: [4, 9], t: parmi(2, 3, 4) } },
      texte: () => ({
        phrases: [`La classe va à la piscine à pied.`, `Les {a|élèves} se mettent en rangs de {b|élèves}.`],
        question: `Combien de rangs y a-t-il ?`,
        labels: { total: 'tous les élèves', nb: 'rangs', taille: 'élèves par rang' },
        juste: `Il y a {r} rangs.`,
        fausses: [`Il y a {r} élèves dans chaque rang.`, `{r} élèves vont à la piscine.`],
      }) },
    // « gagne » dans l'énoncé, mais il faut diviser
    { id: 'paquets-1-074', structure: 'GG', themes: ['ecole'],
      plages: { 2: { n: [2, 9], t: [2, 5] }, 3: { n: [11, 20], t: [2, 5] } },
      texte: A => ({
        phrases: [`En classe, il faut {a|bons points} pour gagner un livre.`, `${A.n} commence à zéro et gagne {b|bons points} chaque jour.`],
        question: `Combien de jours faut-il à ${A.n} pour gagner un livre ?`,
        labels: { total: 'tous les bons points', nb: 'jours', taille: 'bons points par jour' },
        juste: `Il faut {r} jours à ${A.n} pour gagner un livre.`,
        fausses: [`${A.n} gagne {r} bons points chaque jour.`, `Il faut {r} bons points pour gagner un livre.`],
      }) },
    { id: 'paquets-1-075', structure: 'GG', themes: ['ecole'],
      plages: { 3: { n: [11, 20], t: [4, 9] } },
      texte: A => ({
        phrases: [`Pour l'exposition, les élèves de la classe ${A.de} ont fait {a|dessins}.`, `Ils accrochent {b|dessins} sur chaque panneau.`],
        question: `Combien de panneaux faut-il ?`,
        labels: { total: 'tous les dessins', nb: 'panneaux', taille: 'dessins par panneau' },
        juste: `Il faut {r} panneaux.`,
        fausses: [`Il y a {r} dessins sur chaque panneau.`, `Les élèves ont fait {r} dessins.`],
      }) },
    { id: 'paquets-1-076', structure: 'GG', themes: ['ecole'],
      plages: { 2: { n: [2, 9], t: [2, 5] }, 3: { n: [11, 28], t: [2, 6] } },
      texte: () => ({
        phrases: [`Le maître a {a|feuilles} de dessin.`, `Il donne {b|feuilles} à chaque élève, et il ne reste aucune feuille.`],
        question: `Combien d'élèves reçoivent des feuilles ?`,
        labels: { total: 'toutes les feuilles', nb: 'élèves', taille: 'feuilles par élève' },
        juste: `{r} élèves reçoivent des feuilles.`,
        fausses: [`Chaque élève reçoit {r} feuilles.`, `Le maître a {r} feuilles de dessin.`],
      }) },
    { id: 'paquets-1-077', structure: 'GG', themes: ['ecole'],
      plages: { 3: { n: [11, 30], t: [4, 9] } },
      texte: A => ({
        phrases: [`Le livre ${A.de} a {a|pages}.`, `${A.Il} lit {b|pages} chaque soir.`],
        question: `Combien de soirs faut-il à ${A.n} pour lire tout le livre ?`,
        labels: { total: 'toutes les pages', nb: 'soirs', taille: 'pages par soir' },
        juste: `Il faut {r} soirs à ${A.n} pour lire tout le livre.`,
        fausses: [`${A.n} lit {r} pages chaque soir.`, `Le livre a {r} pages.`],
      }) },
    // « combien de fois » : groupement
    { id: 'paquets-1-078', structure: 'GG', themes: ['cuisine'],
      plages: { 2: { n: [2, 9], t: [3, 9] }, 3: { n: [11, 20], t: [5, 9] } },
      texte: A => ({
        phrases: [`${A.n} doit porter {a|pommes} jusqu'à la cuisine.`, `Le panier ${A.de} peut contenir {b|pommes}.`],
        question: `Combien de fois ${A.n} doit-${A.il} remplir son panier ?`,
        labels: { total: 'toutes les pommes', nb: 'paniers remplis', taille: 'pommes par panier' },
        juste: `${A.n} doit remplir son panier {r} fois.`,
        fausses: [`Le panier peut contenir {r} pommes.`, `${A.n} porte {r} pommes en tout.`],
      }) },
    { id: 'paquets-1-079', structure: 'GG', themes: ['fete'],
      plages: { 2: { n: [2, 9], t: [2, 5] }, 3: { n: [11, 15], t: [3, 6] } },
      texte: A => ({
        phrases: [`À la fête foraine, un tour de manège coûte {b|tickets}.`, `${A.n} a {a|tickets}.`],
        question: `Combien de tours de manège ${A.n} peut-${A.il} faire ?`,
        labels: { total: 'tous les tickets', nb: 'tours', taille: 'tickets par tour' },
        juste: `${A.n} peut faire {r} tours de manège.`,
        fausses: [`Un tour de manège coûte {r} tickets.`, `${A.n} a {r} tickets.`],
      }) },
    { id: 'paquets-1-080', structure: 'GG', themes: ['espace'],
      plages: { 2: { n: [2, 9], t: [2, 6] }, 3: { n: [11, 30], t: [2, 6] } },
      texte: () => ({
        phrases: [`Sur la Lune, Alvin fait des bonds de {b|mètres}.`, `Alvin est à {a|mètres} de sa fusée.`],
        question: `Combien de bonds Alvin doit-il faire pour arriver à sa fusée ?`,
        labels: { total: 'toute la distance', nb: 'bonds', taille: 'mètres par bond' },
        juste: `Alvin doit faire {r} bonds pour arriver à sa fusée.`,
        fausses: [`Chaque bond mesure {r} mètres.`, `Alvin est à {r} mètres de sa fusée.`],
      }) },

    // ===== FP : « b fois plus que a » → combien ? =====
    { id: 'paquets-1-081', structure: 'FP', themes: ['fete'],
      texte: (A, B) => ({
        phrases: [`Pour la fête, ${A.n} a gonflé {a|ballons}.`, `${B.n} en a gonflé {b|fois} plus.`],
        question: `Combien de ballons ${B.n} a-t-${B.il} gonflés ?`,
        labels: { petit: A.n, grand: B.n },
        juste: `${B.n} a gonflé {r} ballons.`,
        fausses: [`${A.n} a gonflé {r} ballons.`, `${B.n} a gonflé {r} ballons de plus ${A.que}.`],
      }) },
    { id: 'paquets-1-082', structure: 'FP', themes: ['cuisine', 'jardin'],
      texte: (A, B) => ({
        phrases: [`Au jardin, ${A.n} cueille {a|fraises}.`, `${B.n} cueille {b|fois} plus de fraises.`],
        question: `Combien de fraises ${B.n} cueille-t-${B.il} ?`,
        labels: { petit: A.n, grand: B.n },
        juste: `${B.n} cueille {r} fraises.`,
        fausses: [`${A.n} cueille {r} fraises.`, `${A.n} et ${B.n} cueillent {r} fraises en tout.`],
      }) },
    { id: 'paquets-1-083', structure: 'FP', themes: ['ecole'],
      plages: { 3: { n: [2, 5], t: [20, 60] } },
      texte: (A, B) => ({
        phrases: [`Ce mois-ci, ${A.n} a lu {a|pages}.`, `${B.n} a lu {b|fois} plus de pages.`],
        question: `Combien de pages ${B.n} a-t-${B.il} lues ?`,
        labels: { petit: A.n, grand: B.n },
        juste: `${B.n} a lu {r} pages.`,
        fausses: [`${A.n} a lu {r} pages.`, `${B.n} a lu {r} pages de plus ${A.que}.`],
      }) },
    { id: 'paquets-1-084', structure: 'FP', themes: ['espace'],
      texte: () => ({
        phrases: [`Le petit robot ramasse {a|cristaux}.`, `Le grand robot ramasse {b|fois} plus de cristaux.`],
        question: `Combien de cristaux le grand robot ramasse-t-il ?`,
        labels: { petit: 'petit robot', grand: 'grand robot' },
        juste: `Le grand robot ramasse {r} cristaux.`,
        fausses: [`Le petit robot ramasse {r} cristaux.`, `Les deux robots ramassent {r} cristaux ensemble.`],
      }) },
    { id: 'paquets-1-085', structure: 'FP', themes: ['espace'],
      plages: { 3: [{ n: [2, 5], t: [4, 9] }, { n: [2, 5], t: [11, 20] }] },
      texte: A => ({
        phrases: [`Cette nuit, ${A.n} a vu {a|étoiles filantes}.`, `Avec son télescope, Alvin en a vu {b|fois} plus.`],
        question: `Combien d'étoiles filantes Alvin a-t-il vues ?`,
        labels: { petit: A.n, grand: 'Alvin' },
        juste: `Alvin a vu {r} étoiles filantes.`,
        fausses: [`${A.n} a vu {r} étoiles filantes.`, `Alvin a vu {r} étoiles filantes de plus ${A.que}.`],
      }) },
    { id: 'paquets-1-086', structure: 'FP', themes: ['fete'],
      texte: (A, B) => ({
        phrases: [`Au jeu de fléchettes de la kermesse, ${A.n} marque {a|points}.`, `${B.n} marque {b|fois} plus de points.`],
        question: `Combien de points ${B.n} marque-t-${B.il} ?`,
        labels: { petit: A.n, grand: B.n },
        juste: `${B.n} marque {r} points.`,
        fausses: [`${A.n} marque {r} points.`, `${B.n} marque {r} points de plus ${A.que}.`],
      }) },
    { id: 'paquets-1-087', structure: 'FP', themes: ['cuisine', 'fete'],
      texte: () => ({
        phrases: [`Dans le petit bocal, il y a {a|bonbons}.`, `Le grand bocal contient {b|fois} plus de bonbons.`],
        question: `Combien de bonbons y a-t-il dans le grand bocal ?`,
        labels: { petit: 'petit bocal', grand: 'grand bocal' },
        juste: `Il y a {r} bonbons dans le grand bocal.`,
        fausses: [`Il y a {r} bonbons dans le petit bocal.`, `Il y a {r} bonbons dans les deux bocaux ensemble.`],
      }) },
    { id: 'paquets-1-088', structure: 'FP', themes: ['ecole'],
      plages: { 3: { n: [2, 5], t: [20, 60] } },
      texte: () => ({
        phrases: [`La bibliothèque de la classe compte {a|livres}.`, `La bibliothèque de l'école compte {b|fois} plus de livres.`],
        question: `Combien de livres y a-t-il dans la bibliothèque de l'école ?`,
        labels: { petit: 'la classe', grand: "l'école" },
        juste: `Il y a {r} livres dans la bibliothèque de l'école.`,
        fausses: [`Il y a {r} livres dans la bibliothèque de la classe.`, `L'école a {r} livres de plus que la classe.`],
      }) },

    // ===== Additifs : des « paquets » dans l'énoncé, mais il faut ajouter ou retirer =====
    { id: 'paquets-1-089', structure: 'CT', themes: ['fete'], niveaux: [1, 2], max: 150,
      texte: A => ({
        phrases: [`Pour la fête, ${A.n} achète un paquet de {a|bonbons} à la fraise.`, `${A.Il} achète aussi un paquet de {b|bonbons} à la menthe.`],
        question: `Combien de bonbons ${A.n} a-t-${A.il} en tout ?`,
        labels: { tout: 'tous les bonbons', p1: 'à la fraise', p2: 'à la menthe' },
        juste: `${A.n} a {r} bonbons en tout.`,
        fausses: [`${A.n} a {r} bonbons à la fraise.`, `${A.n} achète {r} paquets de bonbons.`],
      }) },
    { id: 'paquets-1-090', structure: 'TP', themes: ['cuisine'], niveaux: [1, 2], max: 100,
      texte: () => ({
        phrases: [`Une grande boîte contient {a|biscuits}.`, `Pendant le goûter, les enfants mangent {b|biscuits}.`],
        question: `Combien de biscuits reste-t-il dans la boîte ?`,
        labels: { tout: 'au début', p1: 'mangés', p2: 'qui restent' },
        juste: `Il reste {r} biscuits dans la boîte.`,
        fausses: [`Les enfants mangent {r} biscuits.`, `La boîte contenait {r} biscuits au début.`],
      }) },
    { id: 'paquets-1-091', structure: 'CT', themes: ['espace'], niveaux: [1, 2], max: 200,
      texte: () => ({
        phrases: [`Alvin charge deux caisses dans sa fusée.`, `La caisse rouge contient {a|sachets} de croquettes.`, `La caisse bleue contient {b|sachets} de croquettes.`],
        question: `Combien de sachets de croquettes Alvin charge-t-il en tout ?`,
        labels: { tout: 'tous les sachets', p1: 'caisse rouge', p2: 'caisse bleue' },
        juste: `Alvin charge {r} sachets de croquettes en tout.`,
        fausses: [`La caisse rouge contient {r} sachets.`, `La caisse bleue contient {r} sachets.`],
      }) },
    // « distribue » dans l'énoncé, mais il faut soustraire
    { id: 'paquets-1-092', structure: 'TP', themes: ['ecole'], max: 500,
      texte: () => ({
        phrases: [`La maîtresse a un paquet de {a|feuilles}.`, `Elle distribue {b|feuilles} pour le dessin.`],
        question: `Combien de feuilles reste-t-il dans le paquet ?`,
        labels: { tout: 'au début', p1: 'distribuées', p2: 'qui restent' },
        juste: `Il reste {r} feuilles dans le paquet.`,
        fausses: [`La maîtresse distribue {r} feuilles.`, `Le paquet avait {r} feuilles au début.`],
      }) },
    { id: 'paquets-1-093', structure: 'TP', themes: ['fete'], niveaux: [1, 2], max: 60,
      texte: (A, B) => ({
        phrases: [`${A.n} a un sachet de {a|bonbons}.`, `${A.Il} offre {b|bonbons} ${B.a}.`],
        question: `Combien de bonbons reste-t-il à ${A.n} ?`,
        labels: { tout: 'le sachet', p1: 'offerts', p2: 'qui restent' },
        juste: `Il reste {r} bonbons à ${A.n}.`,
        fausses: [`${A.n} offre {r} bonbons ${B.a}.`, `Le sachet contenait {r} bonbons au début.`],
      }) },
  ];

  // Les modèles multiplicatifs sans nombres() sur mesure utilisent les plages (ou les plages par défaut).
  modeles.forEach(m => {
    if (['GT', 'GP', 'GG', 'FP'].includes(m.structure) && !m.nombres) m.nombres = groupes(m.structure, m.plages || {});
  });
  Problemes.ajouter('paquets', modeles);

  // Phrases pièges : un nombre inutile, dans des unités qui ne se mélangent pas aux données des problèmes.
  Problemes.ajouterPieges('paquets', [
    { f: () => `Il y a {d|nuages} dans le ciel.`, v: (niv, rnd) => rnd(3, 12) },
    { f: P => `${P.n} porte un gilet à {d|boutons}.`, v: (niv, rnd) => rnd(3, 8) },
    { f: P => `Ce matin, ${P.n} s'est levé${P.e} à {d|heures}.`, v: (niv, rnd) => rnd(6, 9) },
    { f: P => `${P.n} habite à {d|kilomètres} de l'école.`, v: (niv, rnd) => rnd(2, 9), sansAlvin: true },
    { f: () => `La fusée d'Alvin peut voler {d|jours} sans s'arrêter.`, v: (niv, rnd) => rnd(10, 30) },
  ]);
})();
