'use strict';
/*
 * Plus ou moins — banque 1 : jeux, école, cuisine, sport (+ quelques problèmes espace et voyage).
 * Reprend toutes les variantes de l'ancienne version (js/ancien/problemes.js) et ajoute
 * des situations de la vie de tous les jours : récréation, cantine, classe, anniversaire,
 * kermesse, sport, jeux de société, bibliothèque…
 * Ordre : CT, TG, TP, CP, TTg, TTp, TIg, TIp, CE, CPlus, CMoins, CInvP, CInvM.
 */
Problemes.ajouter('plusmoins', [
  // ===========================================================================
  // CT — combinaison : on cherche le tout (a + b)
  // ===========================================================================
  { id: 'plusmoins-1-001', structure: 'CT', themes: ['jeux'], max: 200, niveaux: [1, 2],
    texte: A => ({
      phrases: [`${A.n} a {a|billes rouges} et {b|billes bleues}.`],
      question: `Combien de billes ${A.n} a-t-${A.il} en tout ?`,
      labels: { tout: 'toutes les billes', p1: 'rouges', p2: 'bleues' },
      juste: `${A.n} a {r} billes en tout.`,
      fausses: [`${A.n} a {r} billes rouges.`, `${A.n} a {r} billes bleues.`],
    }) },
  { id: 'plusmoins-1-002', structure: 'CT', themes: ['jeux'], max: 999, niveaux: [1, 2],
    texte: (A, B, AB) => ({
      phrases: [`${A.n} a {a|cartes}.`, `${B.n} a {b|cartes}.`],
      question: `Combien de cartes ${A.n} et ${B.n} ont-${AB.ils} à ${AB.eux} deux ?`,
      labels: { tout: `à ${AB.eux} deux`, p1: A.n, p2: B.n },
      juste: `À ${AB.eux} deux, ${A.n} et ${B.n} ont {r} cartes.`,
      fausses: [`${A.n} a {r} cartes.`, `${B.n} a {r} cartes de plus ${A.que}.`],
    }) },
  { id: 'plusmoins-1-003', structure: 'CT', themes: ['espace', 'voyage'], max: 9999,
    texte: () => ({
      phrases: [`La fusée d'Alvin parcourt {a|kilomètres} le matin et {b|kilomètres} l'après-midi.`],
      question: `Combien de kilomètres la fusée parcourt-elle dans la journée ?`,
      labels: { tout: 'toute la journée', p1: 'le matin', p2: "l'après-midi" },
      juste: `La fusée parcourt {r} kilomètres dans la journée.`,
      fausses: [`La fusée parcourt {r} kilomètres le matin.`, `La fusée parcourt {r} kilomètres l'après-midi.`],
    }) },
  { id: 'plusmoins-1-004', structure: 'CT', themes: ['espace', 'voyage'], max: 9999,
    texte: () => ({
      phrases: [`Samedi, {a|personnes} ont visité le musée de l'espace.`, `Dimanche, {b|personnes} ont visité le musée.`],
      question: `Combien de personnes ont visité le musée pendant le week-end ?`,
      labels: { tout: 'le week-end', p1: 'samedi', p2: 'dimanche' },
      juste: `Pendant le week-end, {r} personnes ont visité le musée.`,
      fausses: [`Samedi, {r} personnes ont visité le musée.`, `Dimanche, {r} personnes ont visité le musée.`],
    }) },
  { id: 'plusmoins-1-005', structure: 'CT', themes: ['espace'], max: 9999,
    texte: () => ({
      phrases: [`Sur la planète Zorg, Alvin ramasse {a|cristaux bleus} et {b|cristaux verts}.`],
      question: `Combien de cristaux Alvin a-t-il ramassés en tout ?`,
      labels: { tout: 'tous les cristaux', p1: 'bleus', p2: 'verts' },
      juste: `Alvin a ramassé {r} cristaux en tout.`,
      fausses: [`Alvin a ramassé {r} cristaux bleus.`, `Alvin a ramassé {r} cristaux verts.`],
    }) },
  { id: 'plusmoins-1-006', structure: 'CT', themes: ['jeux', 'espace'], max: 9999,
    texte: A => ({
      phrases: [`Au jeu de la galaxie, ${A.n} marque {a|points} à la première partie.`, `À la deuxième partie, ${A.n} marque {b|points}.`],
      question: `Combien de points ${A.n} a-t-${A.il} marqués en tout ?`,
      labels: { tout: 'en tout', p1: '1re partie', p2: '2e partie' },
      juste: `${A.n} a marqué {r} points en tout.`,
      fausses: [`${A.n} a marqué {r} points à la première partie.`, `${A.n} a marqué {r} points à la deuxième partie.`],
    }) },
  // La phrase piège « Dans la classe de…, il y a … élèves » contredirait l'énoncé : pas de piège ici.
  { id: 'plusmoins-1-007', structure: 'CT', themes: ['ecole'], niveaux: [1], sansPiege: true,
    nombres: (niv, rnd) => ({ a: rnd(8, 15), b: rnd(8, 15) }),
    texte: A => ({
      phrases: [`Dans la classe ${A.de}, il y a {a|filles} et {b|garçons}.`],
      question: `Combien d'élèves y a-t-il dans cette classe ?`,
      labels: { tout: 'tous les élèves', p1: 'filles', p2: 'garçons' },
      juste: `Il y a {r} élèves dans cette classe.`,
      fausses: [`Il y a {r} filles dans cette classe.`, `Il y a {r} garçons dans cette classe.`],
    }) },
  { id: 'plusmoins-1-008', structure: 'CT', themes: ['ecole'], max: 999, niveaux: [1, 2],
    texte: () => ({
      phrases: [`À la bibliothèque de l'école, il y a {a|albums} et {b|romans}.`],
      question: `Combien de livres y a-t-il dans la bibliothèque ?`,
      labels: { tout: 'tous les livres', p1: 'albums', p2: 'romans' },
      juste: `Il y a {r} livres dans la bibliothèque.`,
      fausses: [`Il y a {r} albums dans la bibliothèque.`, `Il y a {r} romans dans la bibliothèque.`],
    }) },
  { id: 'plusmoins-1-009', structure: 'CT', themes: ['cuisine', 'ecole'], max: 400, niveaux: [1, 2],
    texte: () => ({
      phrases: [`Aujourd'hui, à la cantine, il y a {a|yaourts à la fraise} et {b|yaourts à la vanille}.`],
      question: `Combien de yaourts y a-t-il à la cantine ?`,
      labels: { tout: 'tous les yaourts', p1: 'à la fraise', p2: 'à la vanille' },
      juste: `Il y a {r} yaourts à la cantine.`,
      fausses: [`Il y a {r} yaourts à la fraise.`, `Il y a {r} yaourts à la vanille.`],
    }) },
  { id: 'plusmoins-1-010', structure: 'CT', themes: ['jeux'], max: 60, niveaux: [1],
    texte: (A, B) => ({
      phrases: [`Pour l'anniversaire ${A.de}, ${B.n} gonfle {a|ballons rouges}.`, `Ensuite, ${B.n} gonfle {b|ballons jaunes}.`],
      question: `Combien de ballons ${B.n} a-t-${B.il} gonflés en tout ?`,
      labels: { tout: 'tous les ballons', p1: 'rouges', p2: 'jaunes' },
      juste: `${B.n} a gonflé {r} ballons en tout.`,
      fausses: [`${B.n} a gonflé {r} ballons rouges.`, `${B.n} a gonflé {r} ballons jaunes.`],
    }) },
  { id: 'plusmoins-1-011', structure: 'CT', themes: ['sport'], niveaux: [1],
    nombres: (niv, rnd) => ({ a: rnd(8, 45), b: rnd(8, 45) }),
    texte: A => ({
      phrases: [`Au basket, l'équipe ${A.de} marque {a|points} pendant la première mi-temps.`, `Pendant la deuxième mi-temps, l'équipe marque {b|points}.`],
      question: `Combien de points l'équipe marque-t-elle pendant tout le match ?`,
      labels: { tout: 'tout le match', p1: '1re mi-temps', p2: '2e mi-temps' },
      juste: `L'équipe marque {r} points pendant tout le match.`,
      fausses: [`L'équipe marque {r} points pendant la première mi-temps.`, `L'équipe marque {r} points pendant la deuxième mi-temps.`],
    }) },
  { id: 'plusmoins-1-012', structure: 'CT', themes: ['sport'], niveaux: [1],
    nombres: (niv, rnd) => ({ a: rnd(5, 25), b: rnd(5, 25) }),
    texte: A => ({
      phrases: [`À la piscine, ${A.n} nage {a|longueurs} le matin.`, `L'après-midi, ${A.n} nage encore {b|longueurs}.`],
      question: `Combien de longueurs ${A.n} a-t-${A.il} nagées dans la journée ?`,
      labels: { tout: 'toute la journée', p1: 'le matin', p2: "l'après-midi" },
      juste: `${A.n} a nagé {r} longueurs dans la journée.`,
      fausses: [`${A.n} a nagé {r} longueurs le matin.`, `${A.n} a nagé {r} longueurs l'après-midi.`],
    }) },
  { id: 'plusmoins-1-013', structure: 'CT', themes: ['jeux', 'ecole'], max: 50, niveaux: [1],
    texte: A => ({
      phrases: [`À la kermesse, ${A.n} gagne {a|tickets} au chamboule-tout.`, `${A.n} gagne aussi {b|tickets} à la pêche aux canards.`],
      question: `Combien de tickets ${A.n} a-t-${A.il} gagnés en tout ?`,
      labels: { tout: 'tous les tickets', p1: 'chamboule-tout', p2: 'pêche aux canards' },
      juste: `${A.n} a gagné {r} tickets en tout.`,
      fausses: [`${A.n} a gagné {r} tickets au chamboule-tout.`, `${A.n} a gagné {r} tickets à la pêche aux canards.`],
    }) },
  { id: 'plusmoins-1-014', structure: 'CT', themes: ['cuisine'], max: 40, niveaux: [1],
    texte: A => ({
      phrases: [`Dans le panier ${A.de}, il y a {a|pommes} et {b|poires}.`],
      question: `Combien de fruits y a-t-il dans le panier ?`,
      labels: { tout: 'tous les fruits', p1: 'pommes', p2: 'poires' },
      juste: `Il y a {r} fruits dans le panier.`,
      fausses: [`Il y a {r} pommes dans le panier.`, `Il y a {r} poires dans le panier.`],
    }) },
  { id: 'plusmoins-1-015', structure: 'CT', themes: ['cuisine', 'ecole'], max: 50, niveaux: [1],
    texte: () => ({
      phrases: [`Pour la fête de l'école, les parents apportent {a|gâteaux au chocolat}.`, `Ils apportent aussi {b|gâteaux aux pommes}.`],
      question: `Combien de gâteaux les parents apportent-ils en tout ?`,
      labels: { tout: 'tous les gâteaux', p1: 'au chocolat', p2: 'aux pommes' },
      juste: `Les parents apportent {r} gâteaux en tout.`,
      fausses: [`Les parents apportent {r} gâteaux au chocolat.`, `Les parents apportent {r} gâteaux aux pommes.`],
    }) },
  { id: 'plusmoins-1-016', structure: 'CT', themes: ['jeux', 'ecole'], max: 80, niveaux: [1],
    texte: () => ({
      phrases: [`À la récréation, {a|enfants} jouent au loup.`, `Pendant ce temps, {b|enfants} sautent à la corde.`],
      question: `Combien d'enfants jouent dans la cour en tout ?`,
      labels: { tout: 'tous les enfants', p1: 'au loup', p2: 'à la corde' },
      juste: `Il y a {r} enfants qui jouent dans la cour.`,
      fausses: [`Il y a {r} enfants qui jouent au loup.`, `Il y a {r} enfants qui sautent à la corde.`],
    }) },
  { id: 'plusmoins-1-017', structure: 'CT', themes: ['sport', 'ecole'], max: 60, niveaux: [1],
    texte: () => ({
      phrases: [`Dans le local de sport, il y a {a|ballons de foot} et {b|ballons de basket}.`],
      question: `Combien de ballons y a-t-il dans le local ?`,
      labels: { tout: 'tous les ballons', p1: 'foot', p2: 'basket' },
      juste: `Il y a {r} ballons dans le local.`,
      fausses: [`Il y a {r} ballons de foot dans le local.`, `Il y a {r} ballons de basket dans le local.`],
    }) },
  { id: 'plusmoins-1-018', structure: 'CT', themes: ['sport', 'voyage'], niveaux: [1],
    nombres: (niv, rnd) => ({ a: rnd(3, 25), b: rnd(3, 25) }),
    texte: A => ({
      phrases: [`Samedi, ${A.n} parcourt {a|kilomètres} à vélo.`, `Dimanche, ${A.n} parcourt {b|kilomètres}.`],
      question: `Combien de kilomètres ${A.n} a-t-${A.il} parcourus pendant le week-end ?`,
      labels: { tout: 'le week-end', p1: 'samedi', p2: 'dimanche' },
      juste: `${A.n} a parcouru {r} kilomètres pendant le week-end.`,
      fausses: [`${A.n} a parcouru {r} kilomètres samedi.`, `${A.n} a parcouru {r} kilomètres dimanche.`],
    }) },
  { id: 'plusmoins-1-019', structure: 'CT', themes: ['cuisine'], max: 200, niveaux: [1, 2],
    texte: () => ({
      phrases: [`Ce matin, le boulanger a fait {a|croissants} et {b|pains au chocolat}.`],
      question: `Combien de viennoiseries le boulanger a-t-il faites ?`,
      labels: { tout: 'toutes les viennoiseries', p1: 'croissants', p2: 'pains au chocolat' },
      juste: `Le boulanger a fait {r} viennoiseries.`,
      fausses: [`Le boulanger a fait {r} croissants.`, `Le boulanger a fait {r} pains au chocolat.`],
    }) },
  { id: 'plusmoins-1-020', structure: 'CT', themes: ['ecole'], max: 60, niveaux: [1],
    texte: () => ({
      phrases: [`Pour la rentrée, la maîtresse distribue {a|cahiers rouges}.`, `Elle distribue aussi {b|cahiers bleus}.`],
      question: `Combien de cahiers la maîtresse distribue-t-elle en tout ?`,
      labels: { tout: 'tous les cahiers', p1: 'rouges', p2: 'bleus' },
      juste: `La maîtresse distribue {r} cahiers en tout.`,
      fausses: [`La maîtresse distribue {r} cahiers rouges.`, `La maîtresse distribue {r} cahiers bleus.`],
    }) },

  // ===========================================================================
  // TG — transformation positive : on cherche l'état final (a + b)
  // ===========================================================================
  { id: 'plusmoins-1-021', structure: 'TG', themes: ['jeux', 'ecole'], max: 200, niveaux: [1, 2],
    texte: A => ({
      phrases: [`${A.n} a {a|billes}.`, `À la récréation, ${A.n} gagne {b|billes}.`],
      question: `Combien de billes ${A.n} a-t-${A.il} maintenant ?`,
      labels: { tout: 'maintenant', p1: 'au début', p2: 'gagnées' },
      juste: `${A.n} a maintenant {r} billes.`,
      fausses: [`${A.n} a gagné {r} billes.`, `${A.n} avait {r} billes au début.`],
    }) },
  { id: 'plusmoins-1-022', structure: 'TG', themes: ['jeux'], max: 999, niveaux: [1, 2],
    texte: (A, B) => ({
      phrases: [`${A.n} a {a|autocollants} dans sa collection.`, `Pour l'anniversaire ${A.de}, ${B.n} lui offre {b|autocollants}.`],
      question: `Combien d'autocollants ${A.n} a-t-${A.il} maintenant ?`,
      labels: { tout: 'maintenant', p1: 'au début', p2: 'reçus' },
      juste: `${A.n} a maintenant {r} autocollants.`,
      fausses: [`${B.n} offre {r} autocollants.`, `${A.n} avait {r} autocollants au début.`],
    }) },
  { id: 'plusmoins-1-023', structure: 'TG', themes: ['espace'], max: 99, niveaux: [1],
    texte: () => ({
      phrases: [`Dans la station spatiale, il y a {a|astronautes}.`, `Une navette amène {b|nouveaux astronautes}.`],
      question: `Combien d'astronautes y a-t-il maintenant dans la station ?`,
      labels: { tout: 'maintenant', p1: 'au début', p2: 'arrivés' },
      juste: `Il y a maintenant {r} astronautes dans la station.`,
      fausses: [`La navette amène {r} astronautes.`, `Il y avait {r} astronautes au début.`],
    }) },
  { id: 'plusmoins-1-024', structure: 'TG', themes: ['jeux', 'espace'], max: 9999,
    texte: A => ({
      phrases: [`${A.n} a {a|points} au jeu de la galaxie.`, `Ensuite, ${A.n} gagne {b|points}.`],
      question: `Combien de points ${A.n} a-t-${A.il} maintenant ?`,
      labels: { tout: 'maintenant', p1: 'au début', p2: 'gagnés' },
      juste: `${A.n} a maintenant {r} points.`,
      fausses: [`${A.n} a gagné {r} points.`, `${A.n} avait {r} points au début.`],
    }) },
  { id: 'plusmoins-1-025', structure: 'TG', themes: ['espace'], max: 9999,
    texte: () => ({
      phrases: [`Alvin a {a|cristaux} dans sa fusée.`, `Sur la Lune, Alvin ramasse {b|cristaux}.`],
      question: `Combien de cristaux Alvin a-t-il maintenant ?`,
      labels: { tout: 'maintenant', p1: 'au début', p2: 'ramassés' },
      juste: `Alvin a maintenant {r} cristaux.`,
      fausses: [`Alvin a ramassé {r} cristaux sur la Lune.`, `Alvin avait {r} cristaux au début.`],
    }) },
  { id: 'plusmoins-1-026', structure: 'TG', themes: ['voyage', 'ecole'], max: 80, niveaux: [1],
    texte: () => ({
      phrases: [`Dans le bus, il y a {a|passagers}.`, `À l'arrêt de l'école, {b|passagers} montent.`],
      question: `Combien de passagers y a-t-il maintenant dans le bus ?`,
      labels: { tout: 'maintenant', p1: 'au début', p2: 'qui montent' },
      juste: `Il y a maintenant {r} passagers dans le bus.`,
      fausses: [`À l'arrêt, {r} passagers montent.`, `Au début, il y avait {r} passagers dans le bus.`],
    }) },
  { id: 'plusmoins-1-027', structure: 'TG', themes: ['cuisine', 'ecole'], max: 200, niveaux: [1, 2],
    texte: () => ({
      phrases: [`Dans le placard de la cantine, il y a {a|paquets de pâtes}.`, `Le livreur apporte {b|paquets de pâtes}.`],
      question: `Combien de paquets de pâtes y a-t-il maintenant dans le placard ?`,
      labels: { tout: 'maintenant', p1: 'au début', p2: 'apportés' },
      juste: `Il y a maintenant {r} paquets de pâtes dans le placard.`,
      fausses: [`Le livreur apporte {r} paquets de pâtes.`, `Au début, il y avait {r} paquets de pâtes dans le placard.`],
    }) },
  { id: 'plusmoins-1-028', structure: 'TG', themes: ['ecole'], max: 999, niveaux: [1, 2],
    texte: () => ({
      phrases: [`À la bibliothèque de l'école, il y a {a|livres}.`, `Cette année, la mairie offre {b|nouveaux livres} à l'école.`],
      question: `Combien de livres y a-t-il maintenant à la bibliothèque ?`,
      labels: { tout: 'maintenant', p1: 'avant', p2: 'nouveaux livres' },
      juste: `Il y a maintenant {r} livres à la bibliothèque.`,
      fausses: [`La mairie offre {r} nouveaux livres.`, `Avant, il y avait {r} livres à la bibliothèque.`],
    }) },
  // Des quantités de farine réalistes (dizaines de grammes) : uniquement au grade 2.
  { id: 'plusmoins-1-029', structure: 'TG', themes: ['cuisine'], niveaux: [2],
    nombres: (niv, rnd) => ({ a: 10 * rnd(10, 40), b: 10 * rnd(5, 30) }),
    texte: A => ({
      phrases: [`Pour faire des crêpes, ${A.n} verse {a|grammes de farine} dans un saladier.`, `Puis ${A.n} ajoute encore {b|grammes de farine}.`],
      question: `Combien de grammes de farine y a-t-il dans le saladier ?`,
      labels: { tout: 'dans le saladier', p1: "d'abord", p2: 'ajoutés' },
      juste: `Il y a {r} grammes de farine dans le saladier.`,
      fausses: [`${A.n} ajoute {r} grammes de farine.`, `${A.n} verse d'abord {r} grammes de farine.`],
    }) },
  { id: 'plusmoins-1-030', structure: 'TG', themes: ['jeux', 'sport'], niveaux: [1],
    nombres: (niv, rnd) => ({ a: rnd(20, 75), b: rnd(3, 20) }),
    texte: A => ({
      phrases: [`Aux fléchettes, ${A.n} a déjà {a|points}.`, `Avec sa dernière fléchette, ${A.n} marque {b|points}.`],
      question: `Combien de points ${A.n} a-t-${A.il} à la fin de la partie ?`,
      labels: { tout: 'à la fin', p1: 'avant', p2: 'dernière fléchette' },
      juste: `À la fin de la partie, ${A.n} a {r} points.`,
      fausses: [`${A.n} marque {r} points avec sa dernière fléchette.`, `Avant sa dernière fléchette, ${A.n} avait {r} points.`],
    }) },
  { id: 'plusmoins-1-031', structure: 'TG', themes: ['jeux'], max: 80, niveaux: [1],
    texte: A => ({
      phrases: [`${A.n} a {a|petites voitures}.`, `Pour son anniversaire, ${A.n} reçoit {b|petites voitures} en cadeau.`],
      question: `Combien de petites voitures ${A.n} a-t-${A.il} maintenant ?`,
      labels: { tout: 'maintenant', p1: 'avant', p2: 'en cadeau' },
      juste: `${A.n} a maintenant {r} petites voitures.`,
      fausses: [`${A.n} reçoit {r} petites voitures en cadeau.`, `Avant, ${A.n} avait {r} petites voitures.`],
    }) },
  { id: 'plusmoins-1-032', structure: 'TG', themes: ['ecole'], max: 90, niveaux: [1],
    texte: A => ({
      phrases: [`Hier, ${A.n} a lu {a|pages} de son livre.`, `Aujourd'hui, ${A.n} lit encore {b|pages}.`],
      question: `Combien de pages ${A.n} a-t-${A.il} lues en tout ?`,
      labels: { tout: 'en tout', p1: 'hier', p2: "aujourd'hui" },
      juste: `${A.n} a lu {r} pages en tout.`,
      fausses: [`Hier, ${A.n} a lu {r} pages.`, `Aujourd'hui, ${A.n} lit {r} pages.`],
    }) },
  { id: 'plusmoins-1-033', structure: 'TG', themes: ['sport'], niveaux: [1],
    nombres: (niv, rnd) => ({ a: rnd(15, 80), b: rnd(2, 9) }),
    texte: A => ({
      phrases: [`Depuis le début de la saison, l'équipe de foot ${A.de} a marqué {a|buts}.`, `Samedi, l'équipe marque encore {b|buts}.`],
      question: `Combien de buts l'équipe a-t-elle marqués en tout ?`,
      labels: { tout: 'en tout', p1: 'avant samedi', p2: 'samedi' },
      juste: `L'équipe a marqué {r} buts en tout.`,
      fausses: [`Samedi, l'équipe marque {r} buts.`, `Avant samedi, l'équipe avait marqué {r} buts.`],
    }) },
  { id: 'plusmoins-1-034', structure: 'TG', themes: ['cuisine'], max: 50, niveaux: [1],
    texte: A => ({
      phrases: [`Dans la corbeille de la cuisine, il y a {a|clémentines}.`, `${A.n} rapporte {b|clémentines} du marché.`],
      question: `Combien de clémentines y a-t-il maintenant dans la corbeille ?`,
      labels: { tout: 'maintenant', p1: 'au début', p2: 'rapportées' },
      juste: `Il y a maintenant {r} clémentines dans la corbeille.`,
      fausses: [`${A.n} rapporte {r} clémentines du marché.`, `Au début, il y avait {r} clémentines dans la corbeille.`],
    }) },
  { id: 'plusmoins-1-035', structure: 'TG', themes: ['ecole', 'jeux'], max: 99, niveaux: [1],
    texte: () => ({
      phrases: [`Dans la cour, {a|enfants} jouent.`, `Après la cantine, {b|enfants} arrivent dans la cour.`],
      question: `Combien d'enfants y a-t-il maintenant dans la cour ?`,
      labels: { tout: 'maintenant', p1: 'au début', p2: 'arrivés' },
      juste: `Il y a maintenant {r} enfants dans la cour.`,
      fausses: [`Après la cantine, {r} enfants arrivent dans la cour.`, `Au début, {r} enfants jouaient dans la cour.`],
    }) },
  { id: 'plusmoins-1-036', structure: 'TG', themes: ['sport', 'jeux'], max: 99, niveaux: [1],
    texte: A => ({
      phrases: [`Pour s'entraîner, ${A.n} fait {a|sauts} à la corde sans s'arrêter.`, `Après une pause, ${A.n} fait encore {b|sauts}.`],
      question: `Combien de sauts ${A.n} a-t-${A.il} faits en tout ?`,
      labels: { tout: 'en tout', p1: 'avant la pause', p2: 'après la pause' },
      juste: `${A.n} a fait {r} sauts en tout.`,
      fausses: [`Avant la pause, ${A.n} a fait {r} sauts.`, `Après la pause, ${A.n} fait {r} sauts.`],
    }) },
  { id: 'plusmoins-1-037', structure: 'TG', themes: ['jeux'], max: 300, niveaux: [1, 2],
    texte: A => ({
      phrases: [`La tour ${A.de} est faite de {a|briques}.`, `${A.n} ajoute encore {b|briques} en haut de la tour.`],
      question: `Combien de briques y a-t-il maintenant dans la tour ?`,
      labels: { tout: 'maintenant', p1: 'au début', p2: 'ajoutées' },
      juste: `Il y a maintenant {r} briques dans la tour.`,
      fausses: [`${A.n} ajoute {r} briques.`, `Au début, la tour avait {r} briques.`],
    }) },
  { id: 'plusmoins-1-038', structure: 'TG', themes: ['cuisine'], max: 40, niveaux: [1],
    texte: A => ({
      phrases: [`Sur l'assiette, il y a {a|crêpes}.`, `Le papa ${A.de} pose dessus {b|crêpes} toutes chaudes.`],
      question: `Combien de crêpes y a-t-il maintenant sur l'assiette ?`,
      labels: { tout: 'maintenant', p1: 'au début', p2: 'ajoutées' },
      juste: `Il y a maintenant {r} crêpes sur l'assiette.`,
      fausses: [`Le papa ${A.de} ajoute {r} crêpes.`, `Au début, il y avait {r} crêpes sur l'assiette.`],
    }) },
  { id: 'plusmoins-1-039', structure: 'TG', themes: ['ecole'], max: 60, niveaux: [1],
    texte: A => ({
      phrases: [`${A.n} a {a|bons points}.`, `Cette semaine, la maîtresse donne encore {b|bons points} ${A.a}.`],
      question: `Combien de bons points ${A.n} a-t-${A.il} maintenant ?`,
      labels: { tout: 'maintenant', p1: 'avant', p2: 'cette semaine' },
      juste: `${A.n} a maintenant {r} bons points.`,
      fausses: [`Cette semaine, ${A.n} reçoit {r} bons points.`, `Avant, ${A.n} avait {r} bons points.`],
    }) },
  { id: 'plusmoins-1-040', structure: 'TG', themes: ['jeux'], niveaux: [1],
    nombres: (niv, rnd) => ({ a: rnd(5, 50), b: rnd(3, 12) }),
    texte: A => ({
      phrases: [`Au jeu de l'oie, le pion ${A.de} est sur la case {a}.`, `${A.n} lance les dés et avance de {b|cases}.`],
      question: `Sur quelle case le pion ${A.de} arrive-t-il ?`,
      labels: { tout: "case d'arrivée", p1: 'case de départ', p2: 'cases avancées' },
      juste: `Le pion ${A.de} arrive sur la case {r}.`,
      fausses: [`Le pion ${A.de} avance de {r} cases.`, `Le pion ${A.de} part de la case {r}.`],
    }) },

  // ===========================================================================
  // TP — transformation négative : on cherche ce qui reste (a − b)
  // ===========================================================================
  { id: 'plusmoins-1-041', structure: 'TP', themes: ['jeux'], max: 200, niveaux: [1, 2],
    texte: A => ({
      phrases: [`${A.n} a {a|billes}.`, `Pendant la partie, ${A.n} perd {b|billes}.`],
      question: `Combien de billes reste-t-il à ${A.n} ?`,
      labels: { tout: 'au début', p1: 'perdues', p2: 'qui restent' },
      juste: `Il reste {r} billes à ${A.n}.`,
      fausses: [`${A.n} a perdu {r} billes.`, `${A.n} avait {r} billes au début.`],
    }) },
  { id: 'plusmoins-1-042', structure: 'TP', themes: ['cuisine', 'jeux'], max: 60, niveaux: [1],
    texte: (A, B) => ({
      phrases: [`Dans le sachet ${A.de}, il y a {a|bonbons}.`, `${A.n} donne {b|bonbons} ${B.a}.`],
      question: `Combien de bonbons reste-t-il dans le sachet ?`,
      labels: { tout: 'au début', p1: 'donnés', p2: 'qui restent' },
      juste: `Il reste {r} bonbons dans le sachet.`,
      fausses: [`${A.n} donne {r} bonbons ${B.a}.`, `Au début, il y avait {r} bonbons dans le sachet.`],
    }) },
  { id: 'plusmoins-1-043', structure: 'TP', themes: ['espace'], max: 999, niveaux: [1, 2],
    texte: () => ({
      phrases: [`Le réservoir de la fusée contient {a|litres de carburant}.`, `Pour décoller, la fusée utilise {b|litres de carburant}.`],
      question: `Combien de litres de carburant reste-t-il dans le réservoir ?`,
      labels: { tout: 'au début', p1: 'utilisés', p2: 'qui restent' },
      juste: `Il reste {r} litres de carburant dans le réservoir.`,
      fausses: [`La fusée utilise {r} litres pour décoller.`, `Le réservoir contenait {r} litres au début.`],
    }) },
  { id: 'plusmoins-1-044', structure: 'TP', themes: ['jeux', 'espace'], max: 9999,
    texte: A => ({
      phrases: [`${A.n} a {a|points} au jeu de la galaxie.`, `${A.n} achète un vaisseau qui coûte {b|points}.`],
      question: `Combien de points reste-t-il à ${A.n} ?`,
      labels: { tout: 'au début', p1: 'dépensés', p2: 'qui restent' },
      juste: `Il reste {r} points à ${A.n}.`,
      fausses: [`Le vaisseau coûte {r} points.`, `${A.n} avait {r} points au début.`],
    }) },
  { id: 'plusmoins-1-045', structure: 'TP', themes: ['espace'], max: 9999,
    texte: () => ({
      phrases: [`Alvin a {a|cristaux}.`, `Pour réparer sa fusée, Alvin utilise {b|cristaux}.`],
      question: `Combien de cristaux reste-t-il à Alvin ?`,
      labels: { tout: 'au début', p1: 'utilisés', p2: 'qui restent' },
      juste: `Il reste {r} cristaux à Alvin.`,
      fausses: [`Alvin utilise {r} cristaux.`, `Alvin avait {r} cristaux au début.`],
    }) },
  { id: 'plusmoins-1-046', structure: 'TP', themes: ['cuisine', 'ecole'], max: 99, niveaux: [1],
    texte: () => ({
      phrases: [`La cantinière a {a|œufs}.`, `Pour faire une omelette géante, la cantinière casse {b|œufs}.`],
      question: `Combien d'œufs reste-t-il à la cantinière ?`,
      labels: { tout: 'au début', p1: 'cassés', p2: 'qui restent' },
      juste: `Il reste {r} œufs à la cantinière.`,
      fausses: [`La cantinière casse {r} œufs.`, `Au début, la cantinière avait {r} œufs.`],
    }) },
  { id: 'plusmoins-1-047', structure: 'TP', themes: ['ecole', 'jeux'], max: 99, niveaux: [1],
    texte: () => ({
      phrases: [`Dans la cour, {a|enfants} jouent.`, `La cloche sonne et {b|enfants} rentrent en classe.`],
      question: `Combien d'enfants restent dans la cour ?`,
      labels: { tout: 'au début', p1: 'rentrés', p2: 'dans la cour' },
      juste: `Il reste {r} enfants dans la cour.`,
      fausses: [`Il y a {r} enfants qui rentrent en classe.`, `Au début, {r} enfants jouaient dans la cour.`],
    }) },
  { id: 'plusmoins-1-048', structure: 'TP', themes: ['voyage'], max: 80, niveaux: [1],
    texte: () => ({
      phrases: [`Dans le bus, il y a {a|passagers}.`, `Devant le marché, {b|passagers} descendent.`],
      question: `Combien de passagers reste-t-il dans le bus ?`,
      labels: { tout: 'au début', p1: 'descendus', p2: 'qui restent' },
      juste: `Il reste {r} passagers dans le bus.`,
      fausses: [`Devant le marché, {r} passagers descendent.`, `Au début, il y avait {r} passagers dans le bus.`],
    }) },
  { id: 'plusmoins-1-049', structure: 'TP', themes: ['cuisine'], max: 60, niveaux: [1],
    texte: A => ({
      phrases: [`${A.n} a préparé {a|biscuits} pour le goûter.`, `Les enfants mangent {b|biscuits}.`],
      question: `Combien de biscuits reste-t-il ?`,
      labels: { tout: 'préparés', p1: 'mangés', p2: 'qui restent' },
      juste: `Il reste {r} biscuits.`,
      fausses: [`Les enfants mangent {r} biscuits.`, `${A.n} a préparé {r} biscuits.`],
    }) },
  { id: 'plusmoins-1-050', structure: 'TP', themes: ['ecole'], max: 9000, niveaux: [2, 3],
    texte: () => ({
      phrases: [`La bibliothèque du village possède {a|livres}.`, `Ce mois-ci, les lecteurs empruntent {b|livres}.`],
      question: `Combien de livres reste-t-il sur les étagères ?`,
      labels: { tout: 'tous les livres', p1: 'empruntés', p2: 'sur les étagères' },
      juste: `Il reste {r} livres sur les étagères.`,
      fausses: [`Les lecteurs empruntent {r} livres.`, `Il y a {r} livres en tout dans la bibliothèque.`],
    }) },
  { id: 'plusmoins-1-051', structure: 'TP', themes: ['sport'], max: 99, niveaux: [1], limites: { b: [3, 30] },
    texte: () => ({
      phrases: [`Le club de tennis a {a|balles}.`, `Pendant l'année, {b|balles} se perdent dans les buissons.`],
      question: `Combien de balles reste-t-il au club ?`,
      labels: { tout: 'au début', p1: 'perdues', p2: 'qui restent' },
      juste: `Il reste {r} balles au club.`,
      fausses: [`Le club perd {r} balles.`, `Au début, le club avait {r} balles.`],
    }) },
  // Aux dames, chaque joueur commence avec 20 pions.
  { id: 'plusmoins-1-052', structure: 'TP', themes: ['jeux'], niveaux: [1],
    nombres: (niv, rnd) => ({ a: 20, b: rnd(3, 17) }),
    texte: (A, B) => ({
      phrases: [`Au début d'une partie de dames, ${A.n} a {a|pions}.`, `Pendant la partie, ${B.n} prend {b|pions} ${A.a}.`],
      question: `Combien de pions reste-t-il à ${A.n} ?`,
      labels: { tout: 'au début', p1: 'pris', p2: 'qui restent' },
      juste: `Il reste {r} pions à ${A.n}.`,
      fausses: [`${B.n} prend {r} pions ${A.a}.`, `Au début, ${A.n} a {r} pions.`],
    }) },
  { id: 'plusmoins-1-053', structure: 'TP', themes: ['jeux'], max: 60, niveaux: [1],
    texte: A => ({
      phrases: [`Pour son anniversaire, ${A.n} gonfle {a|ballons}.`, `Pendant la fête, {b|ballons} éclatent.`],
      question: `Combien de ballons reste-t-il à la fin de la fête ?`,
      labels: { tout: 'gonflés', p1: 'éclatés', p2: 'qui restent' },
      juste: `À la fin de la fête, il reste {r} ballons.`,
      fausses: [`Pendant la fête, {r} ballons éclatent.`, `${A.n} gonfle {r} ballons.`],
    }) },
  // Au plus un tiers des coureurs abandonnent.
  { id: 'plusmoins-1-054', structure: 'TP', themes: ['sport', 'ecole'], niveaux: [1, 2],
    nombres: (niv, rnd) => {
      const a = niv === 1 ? rnd(20, 99) : rnd(100, 300);
      return { a, b: rnd(niv === 1 ? 3 : 11, Math.floor(a / 3)) };
    },
    texte: () => ({
      phrases: [`Au cross de l'école, {a|coureurs} prennent le départ.`, `Fatigués, {b|coureurs} s'arrêtent avant la fin.`],
      question: `Combien de coureurs franchissent la ligne d'arrivée ?`,
      labels: { tout: 'au départ', p1: 'arrêtés', p2: "à l'arrivée" },
      juste: `Il y a {r} coureurs qui franchissent la ligne d'arrivée.`,
      fausses: [`Il y a {r} coureurs qui s'arrêtent avant la fin.`, `Il y a {r} coureurs au départ.`],
    }) },
  { id: 'plusmoins-1-055', structure: 'TP', themes: ['cuisine', 'ecole'], max: 400, niveaux: [1, 2],
    texte: () => ({
      phrases: [`Le cuisinier de la cantine a {a|pommes}.`, `À midi, les élèves mangent {b|pommes}.`],
      question: `Combien de pommes reste-t-il au cuisinier ?`,
      labels: { tout: 'au début', p1: 'mangées', p2: 'qui restent' },
      juste: `Il reste {r} pommes au cuisinier.`,
      fausses: [`Les élèves mangent {r} pommes.`, `Au début, le cuisinier avait {r} pommes.`],
    }) },
  { id: 'plusmoins-1-056', structure: 'TP', themes: ['ecole'], max: 500, niveaux: [1, 2],
    texte: () => ({
      phrases: [`Le paquet de la maîtresse contient {a|feuilles}.`, `La maîtresse distribue {b|feuilles} aux élèves.`],
      question: `Combien de feuilles reste-t-il dans le paquet ?`,
      labels: { tout: 'le paquet', p1: 'distribuées', p2: 'qui restent' },
      juste: `Il reste {r} feuilles dans le paquet.`,
      fausses: [`La maîtresse distribue {r} feuilles.`, `Au début, le paquet contenait {r} feuilles.`],
    }) },
  { id: 'plusmoins-1-057', structure: 'TP', themes: ['cuisine', 'ecole'], max: 40, niveaux: [1],
    texte: () => ({
      phrases: [`Pour le pique-nique de la classe, la maîtresse apporte {a|bouteilles d'eau}.`, `Les enfants boivent {b|bouteilles d'eau}.`],
      question: `Combien de bouteilles d'eau reste-t-il ?`,
      labels: { tout: 'apportées', p1: 'bues', p2: 'qui restent' },
      juste: `Il reste {r} bouteilles d'eau.`,
      fausses: [`Les enfants boivent {r} bouteilles d'eau.`, `La maîtresse apporte {r} bouteilles d'eau.`],
    }) },
  { id: 'plusmoins-1-058', structure: 'TP', themes: ['jeux'], max: 52, niveaux: [1],
    texte: (A, B) => ({
      phrases: [`Au jeu de la bataille, ${A.n} a {a|cartes}.`, `Pendant la partie, ${A.n} perd {b|cartes} contre ${B.n}.`],
      question: `Combien de cartes reste-t-il à ${A.n} ?`,
      labels: { tout: 'au début', p1: 'perdues', p2: 'qui restent' },
      juste: `Il reste {r} cartes à ${A.n}.`,
      fausses: [`${A.n} perd {r} cartes.`, `Au début, ${A.n} a {r} cartes.`],
    }) },

  // ===========================================================================
  // CP — combinaison : on cherche une partie (a − b)
  // ===========================================================================
  { id: 'plusmoins-1-059', structure: 'CP', themes: ['espace', 'voyage'], max: 999, niveaux: [2],
    texte: () => ({
      phrases: [`Dans le grand vaisseau, il y a {a|passagers}.`, `Pendant le voyage, {b|passagers} dorment et les autres regardent les étoiles.`],
      question: `Combien de passagers regardent les étoiles ?`,
      labels: { tout: 'tous les passagers', p1: 'dorment', p2: 'regardent les étoiles' },
      juste: `Il y a {r} passagers qui regardent les étoiles.`,
      fausses: [`Il y a {r} passagers qui dorment.`, `Il y a {r} passagers dans le vaisseau.`],
    }) },
  { id: 'plusmoins-1-060', structure: 'CP', themes: ['jeux'], max: 200, niveaux: [2],
    texte: A => ({
      phrases: [`${A.n} a {a|billes}.`, `Parmi ces billes, {b|billes} sont rouges et les autres sont bleues.`],
      question: `Combien de billes bleues ${A.n} a-t-${A.il} ?`,
      labels: { tout: 'toutes les billes', p1: 'rouges', p2: 'bleues' },
      juste: `${A.n} a {r} billes bleues.`,
      fausses: [`${A.n} a {r} billes rouges.`, `${A.n} a {r} billes en tout.`],
    }) },
  { id: 'plusmoins-1-061', structure: 'CP', themes: ['jeux', 'espace'], max: 9999,
    texte: A => ({
      phrases: [`Pour gagner la coupe des étoiles, il faut {a|points}.`, `${A.n} a déjà {b|points}.`],
      question: `Combien de points ${A.n} doit-${A.il} encore marquer ?`,
      labels: { tout: 'pour gagner', p1: 'déjà', p2: 'encore' },
      juste: `${A.n} doit encore marquer {r} points.`,
      fausses: [`${A.n} a déjà {r} points.`, `Il faut {r} points pour gagner.`],
    }) },
  { id: 'plusmoins-1-062', structure: 'CP', themes: ['ecole'], max: 400, niveaux: [2],
    texte: A => ({
      phrases: [`Le livre « Alvin sur la Lune » a {a|pages}.`, `${A.n} a déjà lu {b|pages}.`],
      question: `Combien de pages ${A.n} doit-${A.il} encore lire pour finir le livre ?`,
      labels: { tout: 'tout le livre', p1: 'déjà lues', p2: 'à lire' },
      juste: `${A.n} doit encore lire {r} pages.`,
      fausses: [`${A.n} a déjà lu {r} pages.`, `Le livre a {r} pages.`],
    }) },
  { id: 'plusmoins-1-063', structure: 'CP', themes: ['espace', 'voyage'], max: 9999,
    texte: () => ({
      phrases: [`Pour aller sur la planète Zorg, la fusée doit parcourir {a|kilomètres}.`, `La fusée a déjà parcouru {b|kilomètres}.`],
      question: `Combien de kilomètres la fusée doit-elle encore parcourir ?`,
      labels: { tout: 'tout le voyage', p1: 'déjà parcourus', p2: 'à parcourir' },
      juste: `La fusée doit encore parcourir {r} kilomètres.`,
      fausses: [`La fusée a déjà parcouru {r} kilomètres.`, `Le voyage fait {r} kilomètres.`],
    }) },
  { id: 'plusmoins-1-064', structure: 'CP', themes: ['ecole', 'cuisine'], max: 600, niveaux: [2],
    texte: () => ({
      phrases: [`L'école compte {a|élèves}.`, `À midi, {b|élèves} mangent à la cantine et les autres rentrent déjeuner à la maison.`],
      question: `Combien d'élèves rentrent déjeuner à la maison ?`,
      labels: { tout: 'tous les élèves', p1: 'à la cantine', p2: 'à la maison' },
      juste: `Il y a {r} élèves qui rentrent déjeuner à la maison.`,
      fausses: [`Il y a {r} élèves qui mangent à la cantine.`, `L'école compte {r} élèves.`],
    }) },
  { id: 'plusmoins-1-065', structure: 'CP', themes: ['sport'], max: 900, niveaux: [2],
    texte: () => ({
      phrases: [`Au club de sport, {a|enfants} sont inscrits.`, `Parmi eux, {b|enfants} font du judo et les autres font de la danse.`],
      question: `Combien d'enfants font de la danse ?`,
      labels: { tout: 'tous les inscrits', p1: 'judo', p2: 'danse' },
      juste: `Il y a {r} enfants qui font de la danse.`,
      fausses: [`Il y a {r} enfants qui font du judo.`, `Il y a {r} enfants inscrits au club.`],
    }) },
  { id: 'plusmoins-1-066', structure: 'CP', themes: ['cuisine'], max: 500, niveaux: [2],
    texte: () => ({
      phrases: [`Le pâtissier a préparé {a|macarons}.`, `Il y a {b|macarons} à la fraise et tous les autres sont au chocolat.`],
      question: `Combien de macarons au chocolat le pâtissier a-t-il préparés ?`,
      labels: { tout: 'tous les macarons', p1: 'à la fraise', p2: 'au chocolat' },
      juste: `Le pâtissier a préparé {r} macarons au chocolat.`,
      fausses: [`Le pâtissier a préparé {r} macarons à la fraise.`, `Le pâtissier a préparé {r} macarons en tout.`],
    }) },
  { id: 'plusmoins-1-067', structure: 'CP', themes: ['jeux'], max: 5000,
    texte: A => ({
      phrases: [`Le puzzle ${A.de} a {a|pièces}.`, `${A.n} a déjà posé {b|pièces}.`],
      question: `Combien de pièces ${A.n} doit-${A.il} encore poser pour finir le puzzle ?`,
      labels: { tout: 'tout le puzzle', p1: 'déjà posées', p2: 'à poser' },
      juste: `${A.n} doit encore poser {r} pièces.`,
      fausses: [`${A.n} a déjà posé {r} pièces.`, `Le puzzle a {r} pièces.`],
    }) },
  { id: 'plusmoins-1-068', structure: 'CP', themes: ['voyage'], max: 999, niveaux: [2],
    texte: A => ({
      phrases: [`Pour aller chez sa grand-mère, ${A.n} doit faire {a|kilomètres} en voiture.`, `La voiture a déjà roulé {b|kilomètres}.`],
      question: `Combien de kilomètres reste-t-il à faire ?`,
      labels: { tout: 'tout le trajet', p1: 'déjà roulés', p2: 'qui restent' },
      juste: `Il reste {r} kilomètres à faire.`,
      fausses: [`La voiture a déjà roulé {r} kilomètres.`, `Le trajet fait {r} kilomètres.`],
    }) },
  { id: 'plusmoins-1-069', structure: 'CP', themes: ['ecole'], max: 999, niveaux: [2],
    texte: () => ({
      phrases: [`À la bibliothèque de l'école, il y a {a|livres}.`, `Il y a {b|albums} et tous les autres livres sont des romans.`],
      question: `Combien de romans y a-t-il à la bibliothèque ?`,
      labels: { tout: 'tous les livres', p1: 'albums', p2: 'romans' },
      juste: `Il y a {r} romans à la bibliothèque.`,
      fausses: [`Il y a {r} albums à la bibliothèque.`, `Il y a {r} livres en tout à la bibliothèque.`],
    }) },
  { id: 'plusmoins-1-070', structure: 'CP', themes: ['sport'], max: 9999,
    texte: () => ({
      phrases: [`Le stade de la ville a {a|places}.`, `Pour le match de rugby, {b|places} sont occupées.`],
      question: `Combien de places restent libres ?`,
      labels: { tout: 'toutes les places', p1: 'occupées', p2: 'libres' },
      juste: `Il reste {r} places libres.`,
      fausses: [`Il y a {r} places occupées.`, `Le stade a {r} places en tout.`],
    }) },
  { id: 'plusmoins-1-071', structure: 'CP', themes: ['cuisine', 'ecole'], max: 300, niveaux: [2],
    texte: () => ({
      phrases: [`Pour la kermesse, il faut {a|crêpes}.`, `Les parents ont déjà fait {b|crêpes}.`],
      question: `Combien de crêpes les parents doivent-ils encore faire ?`,
      labels: { tout: 'il faut', p1: 'déjà faites', p2: 'encore à faire' },
      juste: `Les parents doivent encore faire {r} crêpes.`,
      fausses: [`Les parents ont déjà fait {r} crêpes.`, `Pour la kermesse, il faut {r} crêpes.`],
    }) },

  // ===========================================================================
  // TTg — on cherche ce qui a été gagné (b − a ; a = avant, b = après)
  // ===========================================================================
  { id: 'plusmoins-1-072', structure: 'TTg', themes: ['jeux', 'ecole'], max: 200, niveaux: [2],
    texte: A => ({
      phrases: [`Ce matin, ${A.n} avait {a|billes}.`, `Ce soir, ${A.n} a {b|billes}.`],
      question: `Combien de billes ${A.n} a-t-${A.il} gagnées aujourd'hui ?`,
      labels: { tout: 'ce soir', p1: 'ce matin', p2: 'gagnées' },
      juste: `${A.n} a gagné {r} billes aujourd'hui.`,
      fausses: [`${A.n} a {r} billes ce soir.`, `${A.n} avait {r} billes ce matin.`],
    }) },
  { id: 'plusmoins-1-073', structure: 'TTg', themes: ['jeux', 'espace'], max: 999, niveaux: [2],
    texte: A => ({
      phrases: [`${A.n} a {a|cartes de l'espace}.`, `La collection complète compte {b|cartes}.`],
      question: `Combien de cartes manque-t-il à ${A.n} pour avoir la collection complète ?`,
      labels: { tout: 'collection complète', p1: 'déjà', p2: 'manquantes' },
      juste: `Il manque {r} cartes à ${A.n}.`,
      fausses: [`${A.n} a {r} cartes.`, `La collection complète compte {r} cartes.`],
    }) },
  { id: 'plusmoins-1-074', structure: 'TTg', themes: ['jeux'], max: 9999,
    texte: A => ({
      phrases: [`Au début de la partie, ${A.n} avait {a|points}.`, `À la fin de la partie, ${A.n} a {b|points}.`],
      question: `Combien de points ${A.n} a-t-${A.il} gagnés pendant la partie ?`,
      labels: { tout: 'à la fin', p1: 'au début', p2: 'gagnés' },
      juste: `${A.n} a gagné {r} points pendant la partie.`,
      fausses: [`${A.n} a {r} points à la fin.`, `${A.n} avait {r} points au début.`],
    }) },
  { id: 'plusmoins-1-075', structure: 'TTg', themes: ['ecole'], max: 3000,
    texte: () => ({
      phrases: [`En septembre, il y avait {a|livres} à la bibliothèque de l'école.`, `En juin, il y a {b|livres} à la bibliothèque.`],
      question: `Combien de livres l'école a-t-elle reçus pendant l'année ?`,
      labels: { tout: 'en juin', p1: 'en septembre', p2: 'reçus' },
      juste: `L'école a reçu {r} livres pendant l'année.`,
      fausses: [`En juin, il y a {r} livres à la bibliothèque.`, `En septembre, il y avait {r} livres à la bibliothèque.`],
    }) },
  { id: 'plusmoins-1-076', structure: 'TTg', themes: ['jeux'], max: 9999,
    texte: A => ({
      phrases: [`Avant de jouer, ${A.n} avait {a|pièces d'or} dans son jeu vidéo.`, `Après le niveau du volcan, ${A.n} a {b|pièces d'or}.`],
      question: `Combien de pièces d'or ${A.n} a-t-${A.il} gagnées dans le niveau du volcan ?`,
      labels: { tout: 'après', p1: 'avant', p2: 'gagnées' },
      juste: `${A.n} a gagné {r} pièces d'or dans le niveau du volcan.`,
      fausses: [`Après le niveau du volcan, ${A.n} a {r} pièces d'or.`, `Avant de jouer, ${A.n} avait {r} pièces d'or.`],
    }) },
  { id: 'plusmoins-1-077', structure: 'TTg', themes: ['sport'], max: 9999,
    texte: () => ({
      phrases: [`Au début du match, il y a {a|spectateurs} dans le stade.`, `À la mi-temps, il y a {b|spectateurs}.`],
      question: `Combien de spectateurs sont arrivés pendant la première mi-temps ?`,
      labels: { tout: 'à la mi-temps', p1: 'au début', p2: 'arrivés' },
      juste: `Pendant la première mi-temps, {r} spectateurs sont arrivés.`,
      fausses: [`À la mi-temps, il y a {r} spectateurs.`, `Au début du match, il y a {r} spectateurs.`],
    }) },
  { id: 'plusmoins-1-078', structure: 'TTg', themes: ['ecole'], max: 9999,
    texte: () => ({
      phrases: [`Lundi, il y avait {a|bouchons} dans la caisse de l'école.`, `Vendredi, il y a {b|bouchons} dans la caisse.`],
      question: `Combien de bouchons les élèves ont-ils apportés cette semaine ?`,
      labels: { tout: 'vendredi', p1: 'lundi', p2: 'apportés' },
      juste: `Les élèves ont apporté {r} bouchons cette semaine.`,
      fausses: [`Vendredi, il y a {r} bouchons dans la caisse.`, `Lundi, il y avait {r} bouchons dans la caisse.`],
    }) },

  // ===========================================================================
  // TTp — on cherche ce qui a été perdu ou utilisé (a − b ; a = avant, b = reste)
  // ===========================================================================
  { id: 'plusmoins-1-079', structure: 'TTp', themes: ['cuisine', 'jeux'], max: 99, niveaux: [2],
    texte: A => ({
      phrases: [`Dans la boîte ${A.de}, il y avait {a|bonbons}.`, `Après la fête, il reste {b|bonbons} dans la boîte.`],
      question: `Combien de bonbons les invités ont-ils mangés ?`,
      labels: { tout: 'au début', p1: 'mangés', p2: 'qui restent' },
      juste: `Les invités ont mangé {r} bonbons.`,
      fausses: [`Il reste {r} bonbons dans la boîte.`, `Au début, il y avait {r} bonbons dans la boîte.`],
    }) },
  { id: 'plusmoins-1-080', structure: 'TTp', themes: ['jeux'], max: 999, niveaux: [2],
    texte: A => ({
      phrases: [`${A.n} avait {a|perles}.`, `${A.n} fabrique des bracelets pour toute la classe.`, `Maintenant, il reste {b|perles} à ${A.n}.`],
      question: `Combien de perles ${A.n} a-t-${A.il} utilisées pour les bracelets ?`,
      labels: { tout: 'au début', p1: 'utilisées', p2: 'qui restent' },
      juste: `${A.n} a utilisé {r} perles pour les bracelets.`,
      fausses: [`Il reste {r} perles à ${A.n}.`, `${A.n} avait {r} perles au début.`],
    }) },
  { id: 'plusmoins-1-081', structure: 'TTp', themes: ['espace'], max: 9999,
    texte: () => ({
      phrases: [`Alvin avait {a|cristaux}.`, `Après la réparation de sa fusée, il reste {b|cristaux} à Alvin.`],
      question: `Combien de cristaux Alvin a-t-il utilisés pour la réparation ?`,
      labels: { tout: 'au début', p1: 'utilisés', p2: 'qui restent' },
      juste: `Alvin a utilisé {r} cristaux pour la réparation.`,
      fausses: [`Il reste {r} cristaux à Alvin.`, `Alvin avait {r} cristaux au début.`],
    }) },
  { id: 'plusmoins-1-082', structure: 'TTp', themes: ['cuisine', 'ecole'], max: 900, niveaux: [2],
    texte: () => ({
      phrases: [`Avant le repas, la cantine avait {a|yaourts}.`, `Après le repas, il reste {b|yaourts}.`],
      question: `Combien de yaourts les élèves ont-ils mangés ?`,
      labels: { tout: 'avant le repas', p1: 'mangés', p2: 'qui restent' },
      juste: `Les élèves ont mangé {r} yaourts.`,
      fausses: [`Après le repas, il reste {r} yaourts.`, `Avant le repas, la cantine avait {r} yaourts.`],
    }) },
  { id: 'plusmoins-1-083', structure: 'TTp', themes: ['sport'], max: 200, niveaux: [2], limites: { r: [11, 60] },
    texte: () => ({
      phrases: [`Au début de la saison, le club de foot avait {a|ballons}.`, `Pendant la saison, des ballons se perdent ou crèvent.`, `À la fin de la saison, il reste {b|ballons} au club.`],
      question: `Combien de ballons le club a-t-il perdus pendant la saison ?`,
      labels: { tout: 'au début', p1: 'perdus', p2: 'qui restent' },
      juste: `Le club a perdu {r} ballons pendant la saison.`,
      fausses: [`À la fin de la saison, il reste {r} ballons.`, `Au début de la saison, le club avait {r} ballons.`],
    }) },
  { id: 'plusmoins-1-084', structure: 'TTp', themes: ['jeux'], max: 110, niveaux: [2],
    texte: () => ({
      phrases: [`Au début du jeu, la pioche contient {a|cartes}.`, `Après quelques tours, il reste {b|cartes} dans la pioche.`],
      question: `Combien de cartes les joueurs ont-ils piochées ?`,
      labels: { tout: 'au début', p1: 'piochées', p2: 'qui restent' },
      juste: `Les joueurs ont pioché {r} cartes.`,
      fausses: [`Il reste {r} cartes dans la pioche.`, `Au début, la pioche contient {r} cartes.`],
    }) },
  { id: 'plusmoins-1-085', structure: 'TTp', themes: ['ecole'], max: 500, niveaux: [2],
    texte: () => ({
      phrases: [`En septembre, la classe avait {a|feutres}.`, `En juin, il reste {b|feutres} qui marchent encore.`],
      question: `Combien de feutres sont usés à la fin de l'année ?`,
      labels: { tout: 'en septembre', p1: 'usés', p2: 'qui marchent' },
      juste: `Il y a {r} feutres usés à la fin de l'année.`,
      fausses: [`En juin, il reste {r} feutres qui marchent.`, `En septembre, la classe avait {r} feutres.`],
    }) },
  { id: 'plusmoins-1-086', structure: 'TTp', themes: ['voyage'], max: 999, niveaux: [2],
    texte: () => ({
      phrases: [`Le train part de Paris avec {a|voyageurs}.`, `Aux arrêts, des voyageurs descendent mais personne ne monte.`, `À Lyon, il reste {b|voyageurs} dans le train.`],
      question: `Combien de voyageurs sont descendus avant Lyon ?`,
      labels: { tout: 'au départ', p1: 'descendus', p2: 'à Lyon' },
      juste: `Il y a {r} voyageurs qui sont descendus avant Lyon.`,
      fausses: [`À Lyon, il reste {r} voyageurs dans le train.`, `Le train part de Paris avec {r} voyageurs.`],
    }) },

  // ===========================================================================
  // TIg — on cherche l'état de départ après un gain (b − a ; a = gagné, b = après)
  // Le mot « gagner » pousse à additionner : il faut soustraire.
  // ===========================================================================
  { id: 'plusmoins-1-087', structure: 'TIg', themes: ['jeux', 'espace'], max: 9999,
    texte: A => ({
      phrases: [`${A.n} vient de gagner {a|points} au jeu de la galaxie.`, `Maintenant, ${A.n} a {b|points}.`],
      question: `Combien de points ${A.n} avait-${A.il} avant ?`,
      labels: { tout: 'maintenant', p1: 'avant', p2: 'gagnés' },
      juste: `${A.n} avait {r} points avant.`,
      fausses: [`${A.n} vient de gagner {r} points.`, `${A.n} a maintenant {r} points.`],
    }) },
  { id: 'plusmoins-1-088', structure: 'TIg', themes: ['espace'], max: 9999,
    texte: () => ({
      phrases: [`Sur Mars, Alvin a ramassé {a|cristaux}.`, `Maintenant, Alvin a {b|cristaux} dans sa fusée.`],
      question: `Combien de cristaux Alvin avait-il avant d'aller sur Mars ?`,
      labels: { tout: 'maintenant', p1: 'avant', p2: 'ramassés' },
      juste: `Alvin avait {r} cristaux avant d'aller sur Mars.`,
      fausses: [`Alvin a ramassé {r} cristaux sur Mars.`, `Alvin a maintenant {r} cristaux.`],
    }) },
  { id: 'plusmoins-1-089', structure: 'TIg', themes: ['ecole'], max: 9999,
    texte: () => ({
      phrases: [`Cette année, la bibliothèque de la ville a reçu {a|nouveaux livres}.`, `Maintenant, il y a {b|livres} à la bibliothèque.`],
      question: `Combien de livres y avait-il avant dans la bibliothèque ?`,
      labels: { tout: 'maintenant', p1: 'avant', p2: 'reçus' },
      juste: `Avant, il y avait {r} livres à la bibliothèque.`,
      fausses: [`La bibliothèque de la ville a reçu {r} nouveaux livres.`, `Maintenant, il y a {r} livres à la bibliothèque.`],
    }) },
  { id: 'plusmoins-1-090', structure: 'TIg', themes: ['sport'], max: 9999,
    texte: () => ({
      phrases: [`Pendant la première mi-temps, {a|spectateurs} arrivent encore au stade.`, `À la mi-temps, il y a {b|spectateurs} dans les tribunes.`],
      question: `Combien de spectateurs y avait-il au début du match ?`,
      labels: { tout: 'à la mi-temps', p1: 'au début', p2: 'arrivés' },
      juste: `Au début du match, il y avait {r} spectateurs.`,
      fausses: [`Pendant la première mi-temps, {r} spectateurs arrivent.`, `À la mi-temps, il y a {r} spectateurs.`],
    }) },
  { id: 'plusmoins-1-091', structure: 'TIg', themes: ['jeux'], max: 9999,
    texte: A => ({
      phrases: [`Dans son jeu vidéo, ${A.n} vient de gagner {a|pièces d'or}.`, `Le trésor ${A.de} compte maintenant {b|pièces d'or}.`],
      question: `Combien de pièces d'or ${A.n} avait-${A.il} avant ?`,
      labels: { tout: 'maintenant', p1: 'avant', p2: 'gagnées' },
      juste: `Avant, ${A.n} avait {r} pièces d'or.`,
      fausses: [`${A.n} vient de gagner {r} pièces d'or.`, `Maintenant, ${A.n} a {r} pièces d'or.`],
    }) },
  { id: 'plusmoins-1-092', structure: 'TIg', themes: ['ecole'], max: 9999,
    texte: () => ({
      phrases: [`Cette semaine, les élèves ont apporté {a|bouchons} pour aider une association.`, `Maintenant, il y a {b|bouchons} dans la caisse de l'école.`],
      question: `Combien de bouchons y avait-il dans la caisse avant cette semaine ?`,
      labels: { tout: 'maintenant', p1: 'avant', p2: 'apportés' },
      juste: `Avant cette semaine, il y avait {r} bouchons dans la caisse.`,
      fausses: [`Cette semaine, les élèves ont apporté {r} bouchons.`, `Maintenant, il y a {r} bouchons dans la caisse.`],
    }) },

  // ===========================================================================
  // TIp — on cherche l'état de départ après une perte (a + b ; a = perdu, b = reste)
  // Les mots « dépenser », « utiliser », « reste » poussent à soustraire : il faut additionner.
  // ===========================================================================
  { id: 'plusmoins-1-093', structure: 'TIp', themes: ['jeux', 'espace'], max: 9999,
    texte: A => ({
      phrases: [`Au jeu de la galaxie, ${A.n} a dépensé {a|points} pour acheter un vaisseau.`, `Il reste {b|points} à ${A.n}.`],
      question: `Combien de points ${A.n} avait-${A.il} avant d'acheter le vaisseau ?`,
      labels: { tout: 'avant', p1: 'dépensés', p2: 'qui restent' },
      juste: `${A.n} avait {r} points avant d'acheter le vaisseau.`,
      fausses: [`${A.n} a dépensé {r} points.`, `Il reste {r} points à ${A.n}.`],
    }) },
  { id: 'plusmoins-1-094', structure: 'TIp', themes: ['espace'], max: 9999,
    texte: () => ({
      phrases: [`Alvin a utilisé {a|cristaux} pour réparer sa fusée.`, `Il reste {b|cristaux} à Alvin.`],
      question: `Combien de cristaux Alvin avait-il avant la réparation ?`,
      labels: { tout: 'avant', p1: 'utilisés', p2: 'qui restent' },
      juste: `Alvin avait {r} cristaux avant la réparation.`,
      fausses: [`Alvin a utilisé {r} cristaux.`, `Il reste {r} cristaux à Alvin.`],
    }) },
  { id: 'plusmoins-1-095', structure: 'TIp', themes: ['espace', 'voyage'], max: 9999,
    texte: () => ({
      phrases: [`La fusée a déjà parcouru {a|kilomètres}.`, `Pour arriver sur Jupiter, la fusée doit encore parcourir {b|kilomètres}.`],
      question: `Combien de kilomètres y a-t-il en tout jusqu'à Jupiter ?`,
      labels: { tout: 'tout le voyage', p1: 'déjà parcourus', p2: 'qui restent' },
      juste: `Il y a {r} kilomètres en tout jusqu'à Jupiter.`,
      fausses: [`La fusée a déjà parcouru {r} kilomètres.`, `La fusée doit encore parcourir {r} kilomètres.`],
    }) },
  { id: 'plusmoins-1-096', structure: 'TIp', themes: ['ecole'],
    nombres: (niv, rnd) => ({ a: rnd(100, 1500), b: rnd(1500, 8000) }),
    texte: () => ({
      phrases: [`Ce mois-ci, les lecteurs ont emprunté {a|livres} à la bibliothèque.`, `Il reste {b|livres} sur les étagères.`],
      question: `Au début du mois, combien de livres y avait-il dans la bibliothèque ?`,
      labels: { tout: 'au début du mois', p1: 'empruntés', p2: 'qui restent' },
      juste: `Au début du mois, il y avait {r} livres à la bibliothèque.`,
      fausses: [`Les lecteurs ont emprunté {r} livres.`, `Il reste {r} livres sur les étagères.`],
    }) },
  // Peu d'abandons, beaucoup d'arrivées.
  { id: 'plusmoins-1-097', structure: 'TIp', themes: ['sport'],
    nombres: (niv, rnd) => ({ a: rnd(40, 900), b: rnd(1000, 8000) }),
    texte: () => ({
      phrases: [`Pendant le marathon de la ville, {a|coureurs} ont abandonné.`, `À l'arrivée, on compte {b|coureurs}.`],
      question: `Combien de coureurs ont pris le départ du marathon ?`,
      labels: { tout: 'au départ', p1: 'abandons', p2: "à l'arrivée" },
      juste: `Au départ du marathon, il y avait {r} coureurs.`,
      fausses: [`Pendant le marathon, {r} coureurs ont abandonné.`, `À l'arrivée, on compte {r} coureurs.`],
    }) },
  { id: 'plusmoins-1-098', structure: 'TIp', themes: ['jeux'], max: 9999,
    texte: A => ({
      phrases: [`Dans son jeu vidéo, ${A.n} dépense {a|pièces d'or} pour acheter une épée magique.`, `Après cet achat, il reste {b|pièces d'or} à ${A.n}.`],
      question: `Combien de pièces d'or ${A.n} avait-${A.il} avant d'acheter l'épée ?`,
      labels: { tout: 'avant', p1: 'dépensées', p2: 'qui restent' },
      juste: `Avant d'acheter l'épée, ${A.n} avait {r} pièces d'or.`,
      fausses: [`L'épée coûte {r} pièces d'or.`, `Il reste {r} pièces d'or à ${A.n}.`],
    }) },
  { id: 'plusmoins-1-099', structure: 'TIp', themes: ['cuisine'], max: 3000,
    texte: () => ({
      phrases: [`À la grande fête de la ville, les cuisiniers ont déjà servi {a|crêpes}.`, `Il reste encore {b|crêpes} sur les plateaux.`],
      question: `Combien de crêpes les cuisiniers avaient-ils préparées ?`,
      labels: { tout: 'préparées', p1: 'servies', p2: 'qui restent' },
      juste: `Les cuisiniers avaient préparé {r} crêpes.`,
      fausses: [`Les cuisiniers ont déjà servi {r} crêpes.`, `Il reste {r} crêpes sur les plateaux.`],
    }) },

  // ===========================================================================
  // CE — comparaison : on cherche l'écart (b − a ; a = le plus petit, b = le plus grand)
  // ===========================================================================
  { id: 'plusmoins-1-100', structure: 'CE', themes: ['jeux'], max: 200, niveaux: [2],
    texte: (A, B) => ({
      phrases: [`${A.n} a {a|billes}.`, `${B.n} a {b|billes}.`],
      question: `Combien de billes ${B.n} a-t-${B.il} de plus ${A.que} ?`,
      labels: { grand: B.n, petit: A.n },
      juste: `${B.n} a {r} billes de plus ${A.que}.`,
      fausses: [`${B.n} a {r} billes.`, `${A.n} et ${B.n} ont {r} billes en tout.`],
    }) },
  { id: 'plusmoins-1-101', structure: 'CE', themes: ['jeux', 'espace'], max: 9999,
    texte: (A, B) => ({
      phrases: [`Au jeu de la galaxie, ${A.n} a marqué {a|points}.`, `${B.n} a marqué {b|points}.`],
      question: `Combien de points ${A.n} a-t-${A.il} marqués de moins ${B.que} ?`,
      labels: { grand: B.n, petit: A.n },
      juste: `${A.n} a marqué {r} points de moins ${B.que}.`,
      fausses: [`${A.n} a marqué {r} points.`, `${B.n} a marqué {r} points de moins ${A.que}.`],
    }) },
  { id: 'plusmoins-1-102', structure: 'CE', themes: ['espace', 'voyage'], max: 9999,
    texte: () => ({
      phrases: [`La fusée rouge a parcouru {a|kilomètres}.`, `La fusée bleue a parcouru {b|kilomètres}.`],
      question: `Combien de kilomètres la fusée bleue a-t-elle parcourus de plus que la fusée rouge ?`,
      labels: { grand: 'la fusée bleue', petit: 'la fusée rouge' },
      juste: `La fusée bleue a parcouru {r} kilomètres de plus que la fusée rouge.`,
      fausses: [`La fusée bleue a parcouru {r} kilomètres.`, `La fusée rouge a parcouru {r} kilomètres de plus que la fusée bleue.`],
    }) },
  { id: 'plusmoins-1-103', structure: 'CE', themes: ['sport'], max: 250, niveaux: [2],
    texte: (A, B) => ({
      phrases: [`Cette saison, au basket, ${A.n} a marqué {b|paniers}.`, `${B.n} a marqué {a|paniers}.`],
      question: `Combien de paniers ${B.n} a-t-${B.il} marqués de moins ${A.que} ?`,
      labels: { grand: A.n, petit: B.n },
      juste: `${B.n} a marqué {r} paniers de moins ${A.que}.`,
      fausses: [`${B.n} a marqué {r} paniers.`, `${A.n} a marqué {r} paniers de moins ${B.que}.`],
    }) },
  { id: 'plusmoins-1-104', structure: 'CE', themes: ['ecole'], niveaux: [2],
    nombres: (niv, rnd) => { const a = rnd(80, 450); return { a, b: a + rnd(15, 400) }; },
    texte: () => ({
      phrases: [`L'école du Moulin a {b|élèves}.`, `L'école des Tilleuls a {a|élèves}.`],
      question: `Combien d'élèves l'école du Moulin a-t-elle de plus que l'école des Tilleuls ?`,
      labels: { grand: 'école du Moulin', petit: 'école des Tilleuls' },
      juste: `L'école du Moulin a {r} élèves de plus que l'école des Tilleuls.`,
      fausses: [`L'école du Moulin a {r} élèves.`, `Les deux écoles ont {r} élèves en tout.`],
    }) },
  { id: 'plusmoins-1-105', structure: 'CE', themes: ['cuisine'], max: 900, niveaux: [2],
    texte: () => ({
      phrases: [`Samedi, le boulanger a vendu {b|croissants}.`, `Dimanche, le boulanger a vendu {a|croissants}.`],
      question: `Combien de croissants le boulanger a-t-il vendus de plus samedi que dimanche ?`,
      labels: { grand: 'samedi', petit: 'dimanche' },
      juste: `Le boulanger a vendu {r} croissants de plus samedi que dimanche.`,
      fausses: [`Samedi, le boulanger a vendu {r} croissants.`, `Le boulanger a vendu {r} croissants pendant le week-end.`],
    }) },
  { id: 'plusmoins-1-106', structure: 'CE', themes: ['jeux'], max: 5000,
    texte: (A, B) => ({
      phrases: [`Le puzzle ${A.de} a {a|pièces}.`, `Le puzzle ${B.de} a {b|pièces}.`],
      question: `Combien de pièces le puzzle ${B.de} a-t-il de plus que le puzzle ${A.de} ?`,
      labels: { grand: `puzzle ${B.de}`, petit: `puzzle ${A.de}` },
      juste: `Le puzzle ${B.de} a {r} pièces de plus que le puzzle ${A.de}.`,
      fausses: [`Le puzzle ${B.de} a {r} pièces.`, `Les deux puzzles ont {r} pièces en tout.`],
    }) },
  { id: 'plusmoins-1-107', structure: 'CE', themes: ['voyage'], max: 999, niveaux: [2],
    texte: A => ({
      phrases: [`Pour aller à la mer, la famille ${A.de} roule {b|kilomètres}.`, `Pour aller à la montagne, la famille roule {a|kilomètres}.`],
      question: `Combien de kilomètres de plus faut-il rouler pour aller à la mer ?`,
      labels: { grand: 'la mer', petit: 'la montagne' },
      juste: `Il faut rouler {r} kilomètres de plus pour aller à la mer.`,
      fausses: [`Pour aller à la mer, il faut rouler {r} kilomètres.`, `Pour aller à la montagne, il faut rouler {r} kilomètres.`],
    }) },
  // « encore ramasser » pousse à additionner : il faut chercher l'écart.
  { id: 'plusmoins-1-108', structure: 'CE', themes: ['jeux'], max: 2000,
    texte: (A, B) => ({
      phrases: [`Au jeu de la chasse aux étoiles, ${A.n} a ramassé {b|étoiles}.`, `${B.n} a ramassé {a|étoiles}.`],
      question: `Combien d'étoiles ${B.n} doit-${B.il} encore ramasser pour en avoir autant ${A.que} ?`,
      labels: { grand: A.n, petit: B.n },
      juste: `${B.n} doit encore ramasser {r} étoiles.`,
      fausses: [`${B.n} a ramassé {r} étoiles.`, `${A.n} a ramassé {r} étoiles.`],
    }) },

  // ===========================================================================
  // CPlus — « b de plus que a » : on cherche le plus grand (a + b)
  // ===========================================================================
  { id: 'plusmoins-1-109', structure: 'CPlus', themes: ['jeux'], max: 200, niveaux: [2],
    texte: (A, B) => ({
      phrases: [`${A.n} a {a|billes}.`, `${B.n} a {b|billes} de plus ${A.que}.`],
      question: `Combien de billes ${B.n} a-t-${B.il} ?`,
      labels: { grand: B.n, petit: A.n },
      juste: `${B.n} a {r} billes.`,
      fausses: [`${A.n} a {r} billes.`, `${B.n} a {r} billes de plus ${A.que}.`],
    }) },
  { id: 'plusmoins-1-110', structure: 'CPlus', themes: ['jeux', 'espace'], max: 9999,
    texte: (A, B) => ({
      phrases: [`Au jeu de la galaxie, ${A.n} a marqué {a|points}.`, `${B.n} a marqué {b|points} de plus ${A.que}.`],
      question: `Combien de points ${B.n} a-t-${B.il} marqués ?`,
      labels: { grand: B.n, petit: A.n },
      juste: `${B.n} a marqué {r} points.`,
      fausses: [`${A.n} a marqué {r} points.`, `${B.n} a marqué {r} points de plus ${A.que}.`],
    }) },
  { id: 'plusmoins-1-111', structure: 'CPlus', themes: ['espace'], max: 999, niveaux: [2],
    texte: (A, B) => ({
      phrases: [`Sur la carte du ciel ${A.de}, il y a {a|étoiles}.`, `Sur la carte du ciel ${B.de}, il y a {b|étoiles} de plus que sur la carte ${A.de}.`],
      question: `Combien d'étoiles y a-t-il sur la carte du ciel ${B.de} ?`,
      labels: { grand: `carte ${B.de}`, petit: `carte ${A.de}` },
      juste: `Il y a {r} étoiles sur la carte ${B.de}.`,
      fausses: [`Il y a {r} étoiles sur la carte ${A.de}.`, `Il y a {r} étoiles de plus sur la carte ${B.de}.`],
    }) },
  { id: 'plusmoins-1-112', structure: 'CPlus', themes: ['sport'], max: 9999,
    texte: () => ({
      phrases: [`Samedi, {a|spectateurs} sont venus au stade.`, `Dimanche, il y a eu {b|spectateurs} de plus que samedi.`],
      question: `Combien de spectateurs sont venus au stade dimanche ?`,
      labels: { grand: 'dimanche', petit: 'samedi' },
      juste: `Dimanche, {r} spectateurs sont venus au stade.`,
      fausses: [`Samedi, {r} spectateurs sont venus au stade.`, `Dimanche, il y a eu {r} spectateurs de plus que samedi.`],
    }) },
  { id: 'plusmoins-1-113', structure: 'CPlus', themes: ['ecole'], max: 999, niveaux: [2],
    texte: () => ({
      phrases: [`Pour aider une association, la classe bleue a récolté {a|bouchons}.`, `La classe verte a récolté {b|bouchons} de plus que la classe bleue.`],
      question: `Combien de bouchons la classe verte a-t-elle récoltés ?`,
      labels: { grand: 'classe verte', petit: 'classe bleue' },
      juste: `La classe verte a récolté {r} bouchons.`,
      fausses: [`La classe bleue a récolté {r} bouchons.`, `La classe verte a récolté {r} bouchons de plus que la classe bleue.`],
    }) },
  { id: 'plusmoins-1-114', structure: 'CPlus', themes: ['cuisine', 'ecole'], niveaux: [2],
    nombres: (niv, rnd) => ({ a: rnd(150, 600), b: rnd(15, 200) }),
    texte: () => ({
      phrases: [`Lundi, la cantine a servi {a|repas}.`, `Mardi, la cantine a servi {b|repas} de plus que lundi.`],
      question: `Combien de repas la cantine a-t-elle servis mardi ?`,
      labels: { grand: 'mardi', petit: 'lundi' },
      juste: `Mardi, la cantine a servi {r} repas.`,
      fausses: [`Lundi, la cantine a servi {r} repas.`, `Mardi, la cantine a servi {r} repas de plus que lundi.`],
    }) },
  { id: 'plusmoins-1-115', structure: 'CPlus', themes: ['jeux'], max: 9999,
    texte: (A, B) => ({
      phrases: [`Dans son jeu vidéo, ${A.n} a {a|pièces d'or}.`, `${B.n} a {b|pièces d'or} de plus ${A.que}.`],
      question: `Combien de pièces d'or ${B.n} a-t-${B.il} ?`,
      labels: { grand: B.n, petit: A.n },
      juste: `${B.n} a {r} pièces d'or.`,
      fausses: [`${A.n} a {r} pièces d'or.`, `${B.n} a {r} pièces d'or de plus ${A.que}.`],
    }) },
  { id: 'plusmoins-1-116', structure: 'CPlus', themes: ['sport', 'jeux'], max: 300, niveaux: [2],
    texte: (A, B) => ({
      phrases: [`Au concours de saut à la corde, ${A.n} fait {a|sauts}.`, `${B.n} fait {b|sauts} de plus ${A.que}.`],
      question: `Combien de sauts ${B.n} fait-${B.il} ?`,
      labels: { grand: B.n, petit: A.n },
      juste: `${B.n} fait {r} sauts.`,
      fausses: [`${A.n} fait {r} sauts.`, `${B.n} fait {r} sauts de plus ${A.que}.`],
    }) },

  // ===========================================================================
  // CMoins — « b de moins que a » : on cherche le plus petit (a − b)
  // ===========================================================================
  { id: 'plusmoins-1-117', structure: 'CMoins', themes: ['jeux'], max: 999, niveaux: [2],
    texte: (A, B) => ({
      phrases: [`${A.n} a {a|cartes}.`, `${B.n} a {b|cartes} de moins ${A.que}.`],
      question: `Combien de cartes ${B.n} a-t-${B.il} ?`,
      labels: { grand: A.n, petit: B.n },
      juste: `${B.n} a {r} cartes.`,
      fausses: [`${A.n} a {r} cartes.`, `${B.n} a {r} cartes de moins ${A.que}.`],
    }) },
  { id: 'plusmoins-1-118', structure: 'CMoins', themes: ['espace', 'voyage'], max: 9999,
    texte: () => ({
      phrases: [`La fusée rouge a parcouru {a|kilomètres}.`, `La fusée bleue a parcouru {b|kilomètres} de moins que la fusée rouge.`],
      question: `Combien de kilomètres la fusée bleue a-t-elle parcourus ?`,
      labels: { grand: 'la fusée rouge', petit: 'la fusée bleue' },
      juste: `La fusée bleue a parcouru {r} kilomètres.`,
      fausses: [`La fusée rouge a parcouru {r} kilomètres.`, `La fusée bleue a parcouru {r} kilomètres de moins que la fusée rouge.`],
    }) },
  { id: 'plusmoins-1-119', structure: 'CMoins', themes: ['jeux', 'espace'], max: 9999,
    texte: (A, B) => ({
      phrases: [`${A.n} a {a|points} au jeu de la galaxie.`, `${B.n} a {b|points} de moins ${A.que}.`],
      question: `Combien de points ${B.n} a-t-${B.il} ?`,
      labels: { grand: A.n, petit: B.n },
      juste: `${B.n} a {r} points.`,
      fausses: [`${A.n} a {r} points.`, `${B.n} a {r} points de moins ${A.que}.`],
    }) },
  { id: 'plusmoins-1-120', structure: 'CMoins', themes: ['sport'], max: 500, niveaux: [2],
    texte: () => ({
      phrases: [`Cette année, le club de judo compte {a|enfants}.`, `Le club de danse compte {b|enfants} de moins que le club de judo.`],
      question: `Combien d'enfants le club de danse compte-t-il ?`,
      labels: { grand: 'le judo', petit: 'la danse' },
      juste: `Le club de danse compte {r} enfants.`,
      fausses: [`Le club de judo compte {r} enfants.`, `Le club de danse compte {r} enfants de moins que le club de judo.`],
    }) },
  { id: 'plusmoins-1-121', structure: 'CMoins', themes: ['cuisine'], max: 800, niveaux: [2],
    texte: () => ({
      phrases: [`Samedi, le boulanger fait {a|baguettes}.`, `Dimanche, le boulanger fait {b|baguettes} de moins que samedi.`],
      question: `Combien de baguettes le boulanger fait-il dimanche ?`,
      labels: { grand: 'samedi', petit: 'dimanche' },
      juste: `Dimanche, le boulanger fait {r} baguettes.`,
      fausses: [`Samedi, le boulanger fait {r} baguettes.`, `Dimanche, le boulanger fait {r} baguettes de moins que samedi.`],
    }) },
  { id: 'plusmoins-1-122', structure: 'CMoins', themes: ['ecole'], max: 600, niveaux: [2],
    texte: () => ({
      phrases: [`Pour le spectacle de l'école, la classe verte a vendu {a|tickets}.`, `La classe bleue a vendu {b|tickets} de moins que la classe verte.`],
      question: `Combien de tickets la classe bleue a-t-elle vendus ?`,
      labels: { grand: 'classe verte', petit: 'classe bleue' },
      juste: `La classe bleue a vendu {r} tickets.`,
      fausses: [`La classe verte a vendu {r} tickets.`, `Les deux classes ont vendu {r} tickets en tout.`],
    }) },
  { id: 'plusmoins-1-123', structure: 'CMoins', themes: ['jeux', 'sport'], max: 300, niveaux: [2], limites: { r: [40, 250] },
    texte: (A, B) => ({
      phrases: [`Au bowling, ${A.n} fait {a|points}.`, `${B.n} fait {b|points} de moins ${A.que}.`],
      question: `Combien de points ${B.n} fait-${B.il} ?`,
      labels: { grand: A.n, petit: B.n },
      juste: `${B.n} fait {r} points.`,
      fausses: [`${A.n} fait {r} points.`, `${B.n} fait {r} points de moins ${A.que}.`],
    }) },

  // ===========================================================================
  // CInvP — « a, c'est b de plus que … » : on cherche le plus petit (a − b)
  // Le mot « plus » pousse à additionner : il faut soustraire.
  // ===========================================================================
  { id: 'plusmoins-1-124', structure: 'CInvP', themes: ['jeux', 'espace'], max: 9999,
    texte: (A, B) => ({
      phrases: [`Au jeu de la galaxie, ${A.n} a {a|points}.`, `C'est {b|points} de plus ${B.que}.`],
      question: `Combien de points ${B.n} a-t-${B.il} ?`,
      labels: { grand: A.n, petit: B.n },
      juste: `${B.n} a {r} points.`,
      fausses: [`${A.n} a {r} points.`, `${B.n} a {r} points de plus ${A.que}.`],
    }) },
  { id: 'plusmoins-1-125', structure: 'CInvP', themes: ['espace', 'voyage'], max: 9999,
    texte: () => ({
      phrases: [`La fusée d'Alvin a parcouru {a|kilomètres}.`, `C'est {b|kilomètres} de plus que la fusée de Zorg.`],
      question: `Combien de kilomètres la fusée de Zorg a-t-elle parcourus ?`,
      labels: { grand: "la fusée d'Alvin", petit: 'la fusée de Zorg' },
      juste: `La fusée de Zorg a parcouru {r} kilomètres.`,
      fausses: [`La fusée d'Alvin a parcouru {r} kilomètres.`, `La fusée de Zorg a parcouru {r} kilomètres de plus que la fusée d'Alvin.`],
    }) },
  // Un grand stade (3 000 à 9 999 places) et un gymnase beaucoup plus petit.
  { id: 'plusmoins-1-126', structure: 'CInvP', themes: ['sport'],
    nombres: (niv, rnd) => { const stade = rnd(3000, 9999); return { a: stade, b: stade - rnd(150, 1500) }; },
    texte: () => ({
      phrases: [`Le stade de la ville peut accueillir {a|spectateurs}.`, `C'est {b|spectateurs} de plus que le gymnase.`],
      question: `Combien de spectateurs le gymnase peut-il accueillir ?`,
      labels: { grand: 'le stade', petit: 'le gymnase' },
      juste: `Le gymnase peut accueillir {r} spectateurs.`,
      fausses: [`Le stade peut accueillir {r} spectateurs.`, `Le gymnase peut accueillir {r} spectateurs de plus que le stade.`],
    }) },
  // La bibliothèque de la ville est bien plus grande que celle de l'école.
  { id: 'plusmoins-1-127', structure: 'CInvP', themes: ['ecole'],
    nombres: (niv, rnd) => { const ville = rnd(3000, 9999); return { a: ville, b: ville - rnd(200, 2000) }; },
    texte: () => ({
      phrases: [`La bibliothèque de la ville possède {a|livres}.`, `C'est {b|livres} de plus que la bibliothèque de l'école.`],
      question: `Combien de livres la bibliothèque de l'école possède-t-elle ?`,
      labels: { grand: 'la ville', petit: "l'école" },
      juste: `La bibliothèque de l'école possède {r} livres.`,
      fausses: [`La bibliothèque de la ville possède {r} livres.`, `La bibliothèque de l'école possède {r} livres de plus que celle de la ville.`],
    }) },
  { id: 'plusmoins-1-128', structure: 'CInvP', themes: ['jeux'], max: 9999,
    texte: (A, B) => ({
      phrases: [`Dans son jeu vidéo, ${A.n} a {a|pièces d'or}.`, `C'est {b|pièces d'or} de plus ${B.que}.`],
      question: `Combien de pièces d'or ${B.n} a-t-${B.il} ?`,
      labels: { grand: A.n, petit: B.n },
      juste: `${B.n} a {r} pièces d'or.`,
      fausses: [`${A.n} a {r} pièces d'or.`, `${B.n} a {r} pièces d'or de plus ${A.que}.`],
    }) },
  { id: 'plusmoins-1-129', structure: 'CInvP', themes: ['cuisine'],
    nombres: (niv, rnd) => { const ecart = rnd(40, 900); return { a: rnd(1000, 4000) + ecart, b: ecart }; },
    texte: () => ({
      phrases: [`Cette semaine, la boulangerie a vendu {a|croissants}.`, `C'est {b|croissants} de plus que la semaine dernière.`],
      question: `Combien de croissants la boulangerie a-t-elle vendus la semaine dernière ?`,
      labels: { grand: 'cette semaine', petit: 'semaine dernière' },
      juste: `La semaine dernière, la boulangerie a vendu {r} croissants.`,
      fausses: [`Cette semaine, la boulangerie a vendu {r} croissants.`, `La semaine dernière, la boulangerie a vendu {r} croissants de plus que cette semaine.`],
    }) },

  // ===========================================================================
  // CInvM — « a, c'est b de moins que … » : on cherche le plus grand (a + b)
  // Le mot « moins » pousse à soustraire : il faut additionner.
  // ===========================================================================
  { id: 'plusmoins-1-130', structure: 'CInvM', themes: ['espace'], max: 9999,
    texte: (A, B) => ({
      phrases: [`Sur la planète Zorg, ${A.n} a ramassé {a|cristaux}.`, `C'est {b|cristaux} de moins ${B.que}.`],
      question: `Combien de cristaux ${B.n} a-t-${B.il} ramassés ?`,
      labels: { grand: B.n, petit: A.n },
      juste: `${B.n} a ramassé {r} cristaux.`,
      fausses: [`${A.n} a ramassé {r} cristaux.`, `${B.n} a ramassé {r} cristaux de moins ${A.que}.`],
    }) },
  { id: 'plusmoins-1-131', structure: 'CInvM', themes: ['jeux', 'espace'], max: 9999,
    texte: (A, B) => ({
      phrases: [`Au jeu de la galaxie, ${A.n} a marqué {a|points}.`, `C'est {b|points} de moins ${B.que}.`],
      question: `Combien de points ${B.n} a-t-${B.il} marqués ?`,
      labels: { grand: B.n, petit: A.n },
      juste: `${B.n} a marqué {r} points.`,
      fausses: [`${A.n} a marqué {r} points.`, `${B.n} a marqué {r} points de moins ${A.que}.`],
    }) },
  { id: 'plusmoins-1-132', structure: 'CInvM', themes: ['sport'], max: 9999,
    texte: () => ({
      phrases: [`Cette année, {a|coureurs} ont couru le marathon de la ville.`, `C'est {b|coureurs} de moins que l'année dernière.`],
      question: `Combien de coureurs ont couru le marathon l'année dernière ?`,
      labels: { grand: "l'année dernière", petit: 'cette année' },
      juste: `L'année dernière, {r} coureurs ont couru le marathon.`,
      fausses: [`Cette année, {r} coureurs ont couru le marathon.`, `Cette année, il y a {r} coureurs de plus que l'année dernière.`],
    }) },
  { id: 'plusmoins-1-133', structure: 'CInvM', themes: ['ecole'], max: 9999,
    texte: () => ({
      phrases: [`L'école du Moulin a récolté {a|bouchons}.`, `C'est {b|bouchons} de moins que l'école des Tilleuls.`],
      question: `Combien de bouchons l'école des Tilleuls a-t-elle récoltés ?`,
      labels: { grand: 'école des Tilleuls', petit: 'école du Moulin' },
      juste: `L'école des Tilleuls a récolté {r} bouchons.`,
      fausses: [`L'école du Moulin a récolté {r} bouchons.`, `L'école des Tilleuls a récolté {r} bouchons de moins que l'école du Moulin.`],
    }) },
  { id: 'plusmoins-1-134', structure: 'CInvM', themes: ['voyage'], max: 9999,
    texte: (A, B) => ({
      phrases: [`Cet été, la famille ${A.de} a parcouru {a|kilomètres} en camping-car.`, `C'est {b|kilomètres} de moins que la famille ${B.de}.`],
      question: `Combien de kilomètres la famille ${B.de} a-t-elle parcourus ?`,
      labels: { grand: `famille ${B.de}`, petit: `famille ${A.de}` },
      juste: `La famille ${B.de} a parcouru {r} kilomètres.`,
      fausses: [`La famille ${A.de} a parcouru {r} kilomètres.`, `La famille ${B.de} a parcouru {r} kilomètres de moins que la famille ${A.de}.`],
    }) },
  { id: 'plusmoins-1-135', structure: 'CInvM', themes: ['jeux'], max: 9999,
    texte: A => ({
      phrases: [`Dans le jeu vidéo ${A.de}, le niveau de la forêt rapporte {a|points}.`, `C'est {b|points} de moins que le niveau du château.`],
      question: `Combien de points rapporte le niveau du château ?`,
      labels: { grand: 'le château', petit: 'la forêt' },
      juste: `Le niveau du château rapporte {r} points.`,
      fausses: [`Le niveau de la forêt rapporte {r} points.`, `Le niveau du château rapporte {r} points de moins que la forêt.`],
    }) },
]);

// Phrases pièges propres à la notion (un nombre inutile, sans rapport avec les énoncés).
Problemes.ajouterPieges('plusmoins', [
  { f: P => `Le vélo ${P.de} a {d|vitesses}.`, v: (niv, rnd) => rnd(3, 18) },
  { f: () => `Dehors, il fait {d|degrés}.`, v: (niv, rnd) => rnd(12, 30) },
  { f: P => `${P.n} a {d|cousins}.`, v: (niv, rnd) => rnd(2, 9) },
  { f: P => `La maison ${P.de} a {d|fenêtres}.`, v: (niv, rnd) => rnd(4, 16) },
  { f: () => `Il y a {d|nuages} dans le ciel.`, v: (niv, rnd) => rnd(2, 12) },
]);
